{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "5140a43e-4973-43de-8291-df9a08304591",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "=== Generating Outline ===\n",
      "\n",
      "Here are 5 potential blog heading options for the topic \"Python Lists\":\n",
      "\n",
      "1. **\"List Your Options: A Comprehensive Guide to Python Lists\"**\n",
      "2. **\"Mastering Python Lists: Essential Concepts and Techniques\"**\n",
      "3. **\"The List is Long: Unlocking the Power of Python Lists in Your Code\"**\n",
      "4. **\"List Like a Pro: Best Practices and Tips for Working with Python Lists\"**\n",
      "5. **\"From Indexing to Slicing: A Deep Dive into Python List Operations\"**\n",
      "\n",
      "These headings aim to capture the essence of Python lists, emphasizing their versatility, importance, and the various techniques and best practices involved in working with them.\n",
      "\n",
      "=== Generating Content ===\n",
      "\n",
      "\n",
      "=== Generating Intro & Conclusion ===\n",
      "\n",
      "\n",
      "✅ Blog saved to blog_post.txt\n"
     ]
    }
   ],
   "source": [
    "from groq import Groq\n",
    "\n",
    "client = Groq(api_key=\"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\")\n",
    "MODEL = \"llama-3.1-8b-instant\"\n",
    "\n",
    "\n",
    "def generate_outline(topic):\n",
    "    prompt = f\"Generate 5 blog headings for the topic: {topic}\"\n",
    "\n",
    "    response = client.chat.completions.create(\n",
    "        model=MODEL,\n",
    "        messages=[{\"role\": \"user\", \"content\": prompt}],\n",
    "        temperature=0.7\n",
    "    )\n",
    "\n",
    "    return response.choices[0].message.content\n",
    "\n",
    "\n",
    "def generate_content(headings):\n",
    "    prompt = f\"\"\"\n",
    "Write 2 detailed paragraphs for each of the following blog headings:\n",
    "\n",
    "{headings}\n",
    "\"\"\"\n",
    "\n",
    "    response = client.chat.completions.create(\n",
    "        model=MODEL,\n",
    "        messages=[{\"role\": \"user\", \"content\": prompt}],\n",
    "        temperature=0.7\n",
    "    )\n",
    "\n",
    "    return response.choices[0].message.content\n",
    "\n",
    "\n",
    "\n",
    "def generate_intro_conclusion(topic):\n",
    "    prompt = f\"\"\"\n",
    "Write:\n",
    "1. A 3-sentence introduction\n",
    "2. A 3-sentence conclusion\n",
    "\n",
    "for a blog on: {topic}\n",
    "\"\"\"\n",
    "\n",
    "    response = client.chat.completions.create(\n",
    "        model=MODEL,\n",
    "        messages=[{\"role\": \"user\", \"content\": prompt}],\n",
    "        temperature=0.7\n",
    "    )\n",
    "\n",
    "    return response.choices[0].message.content\n",
    "\n",
    "\n",
    "\n",
    "def build_blog(topic):\n",
    "    print(\"\\n=== Generating Outline ===\\n\")\n",
    "    outline = generate_outline(topic)\n",
    "    print(outline)\n",
    "\n",
    "    print(\"\\n=== Generating Content ===\\n\")\n",
    "    content = generate_content(outline)\n",
    "\n",
    "    print(\"\\n=== Generating Intro & Conclusion ===\\n\")\n",
    "    intro_conclusion = generate_intro_conclusion(topic)\n",
    "\n",
    "    # Assemble full blog\n",
    "    full_blog = f\"\"\"\n",
    "BLOG TITLE: {topic}\n",
    "\n",
    "{intro_conclusion}\n",
    "\n",
    "{content}\n",
    "\"\"\"\n",
    "\n",
    "    return full_blog\n",
    "\n",
    "\n",
    "\n",
    "topic = \"Python Lists\"\n",
    "\n",
    "blog = build_blog(topic)\n",
    "\n",
    "\n",
    "with open(\"blog_post.txt\", \"w\", encoding=\"utf-8\") as f:\n",
    "    f.write(blog)\n",
    "\n",
    "print(\"\\n✅ Blog saved to blog_post.txt\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "30a3e305-269f-44e0-9118-9c2801b99cf6",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
