{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "c92b48f9-365d-47e6-a696-e4ecb78b1ec2",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'faiss'",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mModuleNotFoundError\u001b[39m                       Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[1]\u001b[39m\u001b[32m, line 1\u001b[39m\n\u001b[32m----> \u001b[39m\u001b[32m1\u001b[39m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mfaiss\u001b[39;00m\n\u001b[32m      2\u001b[39m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mnumpy\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mas\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mnp\u001b[39;00m\n\u001b[32m      3\u001b[39m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01msentence_transformers\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m SentenceTransformer\n",
      "\u001b[31mModuleNotFoundError\u001b[39m: No module named 'faiss'"
     ]
    }
   ],
   "source": [
    "import faiss\n",
    "import numpy as np\n",
    "from sentence_transformers import SentenceTransformer\n",
    "import pickle\n",
    "\n",
    "# 1. Sentences\n",
    "sentences = [\n",
    "    # Cricket\n",
    "    \"Virat Kohli scored a century in the match\",\n",
    "    \"The bowler delivered a fast yorker\",\n",
    "    \"India won the cricket match by 5 wickets\",\n",
    "    \"The batsman hit a six over long-on\",\n",
    "\n",
    "    # Cooking\n",
    "    \"I added salt and spices to the curry\",\n",
    "    \"The chef cooked a delicious pasta\",\n",
    "    \"Baking requires precise measurements\",\n",
    "\n",
    "    # Programming\n",
    "    \"Python is a popular programming language\",\n",
    "    \"I wrote a function to sort a list\",\n",
    "    \"Debugging code can be challenging\"\n",
    "]\n",
    "\n",
    "# 2. Load model\n",
    "model = SentenceTransformer('all-MiniLM-L6-v2')\n",
    "\n",
    "# 3. Encode sentences\n",
    "embeddings = model.encode(sentences)\n",
    "embeddings = np.array(embeddings).astype('float32')\n",
    "\n",
    "# 4. Build FAISS index\n",
    "dim = embeddings.shape[1]\n",
    "index = faiss.IndexFlatL2(dim)   # L2 distance\n",
    "index.add(embeddings)\n",
    "\n",
    "# 5. Queries\n",
    "queries = [\n",
    "    \"cricket match performance\",\n",
    "    \"how to cook pasta\",\n",
    "    \"python coding errors\"\n",
    "]\n",
    "\n",
    "def search(query, index, sentences):\n",
    "    q_emb = model.encode([query]).astype('float32')\n",
    "    distances, indices = index.search(q_emb, k=2)\n",
    "\n",
    "    results = []\n",
    "    for i in range(2):\n",
    "        results.append((sentences[indices[0][i]], distances[0][i]))\n",
    "    return results\n",
    "\n",
    "# 6. Run search before saving\n",
    "print(\"🔍 Results BEFORE saving:\\n\")\n",
    "before_results = []\n",
    "\n",
    "for q in queries:\n",
    "    res = search(q, index, sentences)\n",
    "    before_results.append(res)\n",
    "\n",
    "    print(f\"Query: {q}\")\n",
    "    for r in res:\n",
    "        print(f\"  -> {r[0]} (distance: {r[1]:.4f})\")\n",
    "    print()\n",
    "\n",
    "# 7. Save index and sentences\n",
    "faiss.write_index(index, \"faiss_index.bin\")\n",
    "\n",
    "with open(\"documents.pkl\", \"wb\") as f:\n",
    "    pickle.dump(sentences, f)\n",
    "\n",
    "# 8. Reload index and sentences\n",
    "loaded_index = faiss.read_index(\"faiss_index.bin\")\n",
    "\n",
    "with open(\"documents.pkl\", \"rb\") as f:\n",
    "    loaded_sentences = pickle.load(f)\n",
    "\n",
    "# 9. Run search after reload\n",
    "print(\"\\n🔍 Results AFTER loading:\\n\")\n",
    "after_results = []\n",
    "\n",
    "for q in queries:\n",
    "    res = search(q, loaded_index, loaded_sentences)\n",
    "    after_results.append(res)\n",
    "\n",
    "    print(f\"Query: {q}\")\n",
    "    for r in res:\n",
    "        print(f\"  -> {r[0]} (distance: {r[1]:.4f})\")\n",
    "    print()\n",
    "\n",
    "# 10. Verify identical results\n",
    "print(\"✅ Verification:\\n\")\n",
    "\n",
    "for i in range(len(queries)):\n",
    "    print(f\"Query {i+1}: {'MATCH' if before_results[i] == after_results[i] else 'DIFFERENT'}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "c0179d2b-d074-426e-a0c8-1261d45ca897",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting faiss-cpu\n",
      "  Downloading faiss_cpu-1.14.2-cp313-cp313-win_amd64.whl.metadata (7.8 kB)\n",
      "Requirement already satisfied: numpy>=1.25 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from faiss-cpu) (2.3.5)\n",
      "Requirement already satisfied: packaging in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from faiss-cpu) (25.0)\n",
      "Downloading faiss_cpu-1.14.2-cp313-cp313-win_amd64.whl (16.1 MB)\n",
      "   ---------------------------------------- 0.0/16.1 MB ? eta -:--:--\n",
      "    --------------------------------------- 0.3/16.1 MB ? eta -:--:--\n",
      "   - -------------------------------------- 0.8/16.1 MB 2.4 MB/s eta 0:00:07\n",
      "   --- ------------------------------------ 1.6/16.1 MB 2.8 MB/s eta 0:00:06\n",
      "   ------ --------------------------------- 2.6/16.1 MB 3.7 MB/s eta 0:00:04\n",
      "   --------- ------------------------------ 3.7/16.1 MB 4.0 MB/s eta 0:00:04\n",
      "   ------------ --------------------------- 5.0/16.1 MB 4.3 MB/s eta 0:00:03\n",
      "   ---------------- ----------------------- 6.6/16.1 MB 4.8 MB/s eta 0:00:02\n",
      "   -------------------- ------------------- 8.1/16.1 MB 5.3 MB/s eta 0:00:02\n",
      "   ------------------------- -------------- 10.2/16.1 MB 5.7 MB/s eta 0:00:02\n",
      "   ----------------------------- ---------- 11.8/16.1 MB 5.9 MB/s eta 0:00:01\n",
      "   --------------------------------- ------ 13.6/16.1 MB 6.2 MB/s eta 0:00:01\n",
      "   -------------------------------------- - 15.5/16.1 MB 6.4 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 16.1/16.1 MB 6.3 MB/s  0:00:02\n",
      "Installing collected packages: faiss-cpu\n",
      "Successfully installed faiss-cpu-1.14.2\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install faiss-cpu"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "6f78e810-09de-4f21-b86e-1499d85f6081",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "FAISS installed successfully!\n"
     ]
    }
   ],
   "source": [
    "import faiss\n",
    "print(\"FAISS installed successfully!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "f2079fe9-4a1f-457c-bcbe-0f040517403b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "197115559a6e45e587a05a10322150c0",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "🔍 Results BEFORE saving:\n",
      "\n",
      "Query: cricket match performance\n",
      "  -> India won the cricket match by 5 wickets (distance: 0.9156)\n",
      "  -> Virat Kohli scored a century in the match (distance: 1.0339)\n",
      "\n",
      "Query: how to cook pasta\n",
      "  -> The chef cooked a delicious pasta (distance: 0.4077)\n",
      "  -> I added salt and spices to the curry (distance: 1.5802)\n",
      "\n",
      "Query: python coding errors\n",
      "  -> Python is a popular programming language (distance: 0.9996)\n",
      "  -> Debugging code can be challenging (distance: 1.1972)\n",
      "\n",
      "\n",
      "🔍 Results AFTER loading:\n",
      "\n",
      "Query: cricket match performance\n",
      "  -> India won the cricket match by 5 wickets (distance: 0.9156)\n",
      "  -> Virat Kohli scored a century in the match (distance: 1.0339)\n",
      "\n",
      "Query: how to cook pasta\n",
      "  -> The chef cooked a delicious pasta (distance: 0.4077)\n",
      "  -> I added salt and spices to the curry (distance: 1.5802)\n",
      "\n",
      "Query: python coding errors\n",
      "  -> Python is a popular programming language (distance: 0.9996)\n",
      "  -> Debugging code can be challenging (distance: 1.1972)\n",
      "\n",
      "✅ Verification:\n",
      "\n",
      "Query 1: MATCH\n",
      "Query 2: MATCH\n",
      "Query 3: MATCH\n"
     ]
    }
   ],
   "source": [
    "import faiss\n",
    "import numpy as np\n",
    "from sentence_transformers import SentenceTransformer\n",
    "import pickle\n",
    "\n",
    "\n",
    "sentences = [\n",
    " \n",
    "    \"Virat Kohli scored a century in the match\",\n",
    "    \"The bowler delivered a fast yorker\",\n",
    "    \"India won the cricket match by 5 wickets\",\n",
    "    \"The batsman hit a six over long-on\",\n",
    "\n",
    "  g\n",
    "    \"I added salt and spices to the curry\",\n",
    "    \"The chef cooked a delicious pasta\",\n",
    "    \"Baking requires precise measurements\",\n",
    "\n",
    "   \n",
    "    \"Python is a popular programming language\",\n",
    "    \"I wrote a function to sort a list\",\n",
    "    \"Debugging code can be challenging\"\n",
    "]\n",
    "\n",
    "\n",
    "model = SentenceTransformer('all-MiniLM-L6-v2')\n",
    "\n",
    "\n",
    "embeddings = model.encode(sentences)\n",
    "embeddings = np.array(embeddings).astype('float32')\n",
    "\n",
    "\n",
    "dim = embeddings.shape[1]\n",
    "index = faiss.IndexFlatL2(dim)   # L2 distance\n",
    "index.add(embeddings)\n",
    "\n",
    "\n",
    "queries = [\n",
    "    \"cricket match performance\",\n",
    "    \"how to cook pasta\",\n",
    "    \"python coding errors\"\n",
    "]\n",
    "\n",
    "def search(query, index, sentences):\n",
    "    q_emb = model.encode([query]).astype('float32')\n",
    "    distances, indices = index.search(q_emb, k=2)\n",
    "\n",
    "    results = []\n",
    "    for i in range(2):\n",
    "        results.append((sentences[indices[0][i]], distances[0][i]))\n",
    "    return results\n",
    "\n",
    "print(\"🔍 Results BEFORE saving:\\n\")\n",
    "before_results = []\n",
    "\n",
    "for q in queries:\n",
    "    res = search(q, index, sentences)\n",
    "    before_results.append(res)\n",
    "\n",
    "    print(f\"Query: {q}\")\n",
    "    for r in res:\n",
    "        print(f\"  -> {r[0]} (distance: {r[1]:.4f})\")\n",
    "    print()\n",
    "\n",
    "faiss.write_index(index, \"faiss_index.bin\")\n",
    "\n",
    "with open(\"documents.pkl\", \"wb\") as f:\n",
    "    pickle.dump(sentences, f)\n",
    "\n",
    "\n",
    "loaded_index = faiss.read_index(\"faiss_index.bin\")\n",
    "\n",
    "with open(\"documents.pkl\", \"rb\") as f:\n",
    "    loaded_sentences = pickle.load(f)\n",
    "\n",
    "\n",
    "print(\"\\n🔍 Results AFTER loading:\\n\")\n",
    "after_results = []\n",
    "\n",
    "for q in queries:\n",
    "    res = search(q, loaded_index, loaded_sentences)\n",
    "    after_results.append(res)\n",
    "\n",
    "    print(f\"Query: {q}\")\n",
    "    for r in res:\n",
    "        print(f\"  -> {r[0]} (distance: {r[1]:.4f})\")\n",
    "    print()\n",
    "\n",
    "\n",
    "print(\"✅ Verification:\\n\")\n",
    "\n",
    "for i in range(len(queries)):\n",
    "    print(f\"Query {i+1}: {'MATCH' if before_results[i] == after_results[i] else 'DIFFERENT'}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2c4bb583-d01f-466c-b3d0-3a7d3b8daeb1",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
