{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "fbff28a0-1c1f-4c1a-96df-bbf7b87fe69c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: langchain in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (1.3.2)\n",
      "Requirement already satisfied: langchain-groq in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (1.1.2)\n",
      "Requirement already satisfied: langchain-core<2.0.0,>=1.4.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain) (1.4.0)\n",
      "Requirement already satisfied: langgraph<1.3.0,>=1.2.2 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain) (1.2.2)\n",
      "Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain) (2.12.4)\n",
      "Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (1.33)\n",
      "Requirement already satisfied: langchain-protocol>=0.0.14 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (0.0.15)\n",
      "Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (0.8.5)\n",
      "Requirement already satisfied: packaging>=23.2.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (25.0)\n",
      "Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (6.0.3)\n",
      "Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (9.1.2)\n",
      "Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (4.15.0)\n",
      "Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (0.16.0)\n",
      "Requirement already satisfied: jsonpointer>=1.9 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.0->langchain) (3.0.0)\n",
      "Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.1.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langgraph<1.3.0,>=1.2.2->langchain) (4.1.1)\n",
      "Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langgraph<1.3.0,>=1.2.2->langchain) (1.1.0)\n",
      "Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langgraph<1.3.0,>=1.2.2->langchain) (0.3.15)\n",
      "Requirement already satisfied: xxhash>=3.5.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langgraph<1.3.0,>=1.2.2->langchain) (3.7.0)\n",
      "Requirement already satisfied: ormsgpack>=1.12.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.2->langchain) (1.12.2)\n",
      "Requirement already satisfied: httpx>=0.25.2 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (0.28.1)\n",
      "Requirement already satisfied: orjson>=3.11.5 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (3.11.9)\n",
      "Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (1.0.0)\n",
      "Requirement already satisfied: requests>=2.0.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (2.32.5)\n",
      "Requirement already satisfied: zstandard>=0.23.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (0.24.0)\n",
      "Requirement already satisfied: anyio in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (4.10.0)\n",
      "Requirement already satisfied: certifi in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (2026.4.22)\n",
      "Requirement already satisfied: httpcore==1.* in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (1.0.9)\n",
      "Requirement already satisfied: idna in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (3.11)\n",
      "Requirement already satisfied: h11>=0.16 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (0.16.0)\n",
      "Requirement already satisfied: annotated-types>=0.6.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.41.5 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.5)\n",
      "Requirement already satisfied: typing-inspection>=0.4.2 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)\n",
      "Requirement already satisfied: groq<1.0.0,>=0.30.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-groq) (0.37.1)\n",
      "Requirement already satisfied: distro<2,>=1.7.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (1.9.0)\n",
      "Requirement already satisfied: sniffio in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (1.3.0)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (3.4.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (2.5.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install langchain langchain-groq"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "c33cc3be-a9aa-441f-aff3-f59ffa9f8971",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: langchain in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (1.3.2)\n",
      "Requirement already satisfied: langchain-groq in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (1.1.2)\n",
      "Requirement already satisfied: langchain-core<2.0.0,>=1.4.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain) (1.4.0)\n",
      "Requirement already satisfied: langgraph<1.3.0,>=1.2.2 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain) (1.2.2)\n",
      "Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain) (2.12.4)\n",
      "Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (1.33)\n",
      "Requirement already satisfied: langchain-protocol>=0.0.14 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (0.0.15)\n",
      "Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (0.8.5)\n",
      "Requirement already satisfied: packaging>=23.2.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (25.0)\n",
      "Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (6.0.3)\n",
      "Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (9.1.2)\n",
      "Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (4.15.0)\n",
      "Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (0.16.0)\n",
      "Requirement already satisfied: jsonpointer>=1.9 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.0->langchain) (3.0.0)\n",
      "Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.1.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langgraph<1.3.0,>=1.2.2->langchain) (4.1.1)\n",
      "Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langgraph<1.3.0,>=1.2.2->langchain) (1.1.0)\n",
      "Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langgraph<1.3.0,>=1.2.2->langchain) (0.3.15)\n",
      "Requirement already satisfied: xxhash>=3.5.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langgraph<1.3.0,>=1.2.2->langchain) (3.7.0)\n",
      "Requirement already satisfied: ormsgpack>=1.12.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.2->langchain) (1.12.2)\n",
      "Requirement already satisfied: httpx>=0.25.2 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (0.28.1)\n",
      "Requirement already satisfied: orjson>=3.11.5 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (3.11.9)\n",
      "Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (1.0.0)\n",
      "Requirement already satisfied: requests>=2.0.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (2.32.5)\n",
      "Requirement already satisfied: zstandard>=0.23.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (0.24.0)\n",
      "Requirement already satisfied: anyio in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (4.10.0)\n",
      "Requirement already satisfied: certifi in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (2026.4.22)\n",
      "Requirement already satisfied: httpcore==1.* in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (1.0.9)\n",
      "Requirement already satisfied: idna in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (3.11)\n",
      "Requirement already satisfied: h11>=0.16 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (0.16.0)\n",
      "Requirement already satisfied: annotated-types>=0.6.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.41.5 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.5)\n",
      "Requirement already satisfied: typing-inspection>=0.4.2 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)\n",
      "Requirement already satisfied: groq<1.0.0,>=0.30.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-groq) (0.37.1)\n",
      "Requirement already satisfied: distro<2,>=1.7.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (1.9.0)\n",
      "Requirement already satisfied: sniffio in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (1.3.0)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (3.4.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (2.5.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install langchain langchain-groq"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "9b54da98-abb3-4cd3-8d75-34a321dd1569",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "=== OUTPUT 1 ===\n",
      "\n",
      "**Python Lists: A Comprehensive Guide**\n",
      "\n",
      "**What is a Python List?**\n",
      "\n",
      "* A Python list is a collection of items that can be of any data type, including strings, integers, floats, and other lists.\n",
      "* Lists are denoted by square brackets `[]` and are ordered, meaning that each item has a specific index.\n",
      "\n",
      "**Creating a Python List**\n",
      "\n",
      "* You can create a list by assigning a list of values to a variable, for example: `my_list = [1, 2, 3, 4, 5]`.\n",
      "* You can also create an empty list and then add items to it using the `append()` method.\n",
      "* You can create a list from a string using the `split()` method.\n",
      "\n",
      "**Indexing and Slicing**\n",
      "\n",
      "* Each item in a list has a specific index, which is a number that starts from 0.\n",
      "* You can access an item in a list by its index, for example: `my_list[0]` returns the first item in the list.\n",
      "* You can slice a list to extract a subset of items, for example: `my_list[1:3]` returns a list containing the second and third items.\n",
      "* You can also use negative indices to access items from the end of the list.\n",
      "\n",
      "**List Methods**\n",
      "\n",
      "* `append(item)`: adds an item to the end of the list.\n",
      "* `extend(iterable)`: adds multiple items to the end of the list.\n",
      "* `insert(index, item)`: inserts an item at a specific index.\n",
      "* `remove(item)`: removes the first occurrence of an item.\n",
      "* `pop(index)`: removes and returns the item at a specific index.\n",
      "* `index(item)`: returns the index of the first occurrence of an item.\n",
      "* `count(item)`: returns the number of occurrences of an item.\n",
      "\n",
      "**List Operations**\n",
      "\n",
      "* `+`: concatenates two lists.\n",
      "* `*`: repeats a list.\n",
      "* `in`: checks if an item is in a list.\n",
      "* `not in`: checks if an item is not in a list.\n",
      "\n",
      "**Example Use Cases**\n",
      "\n",
      "* Storing a collection of values, such as a list of names or ages.\n",
      "* Processing a list of items, such as sorting a list of numbers.\n",
      "* Working with a list of strings, such as splitting a string into individual words.\n",
      "\n",
      "**Best Practices**\n",
      "\n",
      "* Use meaningful variable names to make your code easier to read.\n",
      "* Use list methods instead of indexing and slicing to make your code more efficient.\n",
      "* Use loops to iterate over a list instead of indexing and slicing.\n",
      "* Use list comprehensions to create a new list from an existing list.\n",
      "\n",
      "=== OUTPUT 2 ===\n",
      "\n",
      "**Loops in Python: A Beginner-Friendly Explanation**\n",
      "\n",
      "**What are Loops?**\n",
      "Loops are a way to repeat a set of instructions in Python. They allow you to execute the same code multiple times without having to write it over and over again.\n",
      "\n",
      "**Types of Loops**\n",
      "There are two main types of loops in Python:\n",
      "\n",
      "1. **For Loop**: Used to iterate over a sequence (like a list or string) and execute a block of code for each item.\n",
      "2. **While Loop**: Used to execute a block of code as long as a certain condition is true.\n",
      "\n",
      "**For Loop Syntax**\n",
      "```python\n",
      "for variable in sequence:\n",
      "    # code to be executed\n",
      "```\n",
      "**Example:**\n",
      "```python\n",
      "fruits = ['apple', 'banana', 'cherry']\n",
      "for fruit in fruits:\n",
      "    print(fruit)\n",
      "```\n",
      "This will output:\n",
      "```\n",
      "apple\n",
      "banana\n",
      "cherry\n",
      "```\n",
      "**While Loop Syntax**\n",
      "```python\n",
      "while condition:\n",
      "    # code to be executed\n",
      "```\n",
      "**Example:**\n",
      "```python\n",
      "i = 0\n",
      "while i < 5:\n",
      "    print(i)\n",
      "    i += 1\n",
      "```\n",
      "This will output:\n",
      "```\n",
      "0\n",
      "1\n",
      "2\n",
      "3\n",
      "4\n",
      "```\n",
      "**Break and Continue Statements**\n",
      "\n",
      "* **Break Statement**: Used to exit a loop prematurely.\n",
      "* **Continue Statement**: Used to skip the rest of the code in a loop and move on to the next iteration.\n",
      "\n",
      "**Example:**\n",
      "```python\n",
      "for i in range(5):\n",
      "    if i == 3:\n",
      "        break\n",
      "    print(i)\n",
      "```\n",
      "This will output:\n",
      "```\n",
      "0\n",
      "1\n",
      "2\n",
      "```\n",
      "**Loop Control Variables**\n",
      "\n",
      "* **Range Function**: Used to generate a sequence of numbers.\n",
      "* **Enumerate Function**: Used to iterate over a sequence and keep track of the index.\n",
      "\n",
      "**Example:**\n",
      "```python\n",
      "for i, fruit in enumerate(fruits):\n",
      "    print(f'{i}: {fruit}')\n",
      "```\n",
      "This will output:\n",
      "```\n",
      "0: apple\n",
      "1: banana\n",
      "2: cherry\n",
      "```\n",
      "**Conclusion**\n",
      "\n",
      "Loops are a powerful tool in Python that allow you to repeat code and execute it multiple times. With practice, you'll become more comfortable using loops to solve problems and automate tasks.\n",
      "\n",
      "=== OUTPUT 3 ===\n",
      "\n",
      "**Recursion: A Step-by-Step Explanation**\n",
      "\n",
      "**Step 1: Introduction to Recursion**\n",
      "\n",
      "Recursion is a programming concept where a function calls itself repeatedly until it reaches a base case that stops the recursion. This process allows the function to solve problems that have overlapping sub-problems, making it an efficient approach for solving certain types of problems.\n",
      "\n",
      "**Step 2: Key Components of Recursion**\n",
      "\n",
      "To understand recursion, you need to know about the following key components:\n",
      "\n",
      "* **Base Case**: The base case is the condition that stops the recursion. It's the point at which the function will no longer call itself.\n",
      "* **Recursive Case**: The recursive case is the part of the function that calls itself. It's the part that breaks down the problem into smaller sub-problems.\n",
      "* **Stack**: The stack is a data structure that stores the function calls. Each time a function calls itself, its state is pushed onto the stack.\n",
      "\n",
      "**Step 3: How Recursion Works**\n",
      "\n",
      "Here's a step-by-step explanation of how recursion works:\n",
      "\n",
      "1. A function is called, and its state is pushed onto the stack.\n",
      "2. The function checks if it has reached the base case. If it has, the function returns its value, and the recursion stops.\n",
      "3. If the function hasn't reached the base case, it calls itself with a smaller instance of the problem.\n",
      "4. The new function call is pushed onto the stack.\n",
      "5. Steps 2-4 are repeated until the base case is reached.\n",
      "6. When the base case is reached, the function returns its value, and the recursion stops.\n",
      "7. The stack is popped, and the previous function call returns its value.\n",
      "\n",
      "**Step 4: Example of Recursion**\n",
      "\n",
      "Let's consider a simple example of recursion: calculating the factorial of a number.\n",
      "\n",
      "```python\n",
      "def factorial(n):\n",
      "    if n == 0:  # base case\n",
      "        return 1\n",
      "    else:\n",
      "        return n * factorial(n-1)  # recursive case\n",
      "```\n",
      "\n",
      "In this example, the `factorial` function calls itself with decreasing values of `n` until it reaches the base case (`n == 0`). The function then returns the product of all the numbers from `n` down to 1.\n",
      "\n",
      "**Step 5: Advantages and Disadvantages of Recursion**\n",
      "\n",
      "Recursion has several advantages, including:\n",
      "\n",
      "* It allows for elegant solutions to complex problems.\n",
      "* It can be more efficient than iterative solutions for certain problems.\n",
      "\n",
      "However, recursion also has some disadvantages:\n",
      "\n",
      "* It can be slower than iterative solutions due to the overhead of function calls.\n",
      "* It can cause stack overflow errors if the recursion is too deep.\n",
      "\n",
      "**Step 6: Conclusion**\n",
      "\n",
      "In conclusion, recursion is a powerful programming concept that can be used to solve complex problems. However, it requires careful consideration of the base case and the recursive case to avoid stack overflow errors and optimize performance. With practice and experience, you can master the art of recursion and write more efficient and elegant code.\n",
      "\n",
      "=== OUTPUT 4 ===\n",
      "\n",
      "**Interviewer:** Good morning, today we are going to discuss one of the fundamental concepts in programming: Object-Oriented Programming (OOP) concepts. Let's dive right in.\n",
      "\n",
      "**Q1: What are Object-Oriented Programming (OOP) concepts?**\n",
      "\n",
      "**Me:** Object-Oriented Programming (OOP) is a programming paradigm that revolves around the concept of objects and classes. It's a way of designing and organizing code to make it more modular, reusable, and maintainable. OOP concepts include abstraction, encapsulation, inheritance, polymorphism, and composition.\n",
      "\n",
      "**Q2: What is Abstraction in OOP?**\n",
      "\n",
      "**Me:** Abstraction is the concept of hiding the implementation details of an object from the outside world, while exposing only the necessary information. It's a way of showing only the essential features of an object without revealing how it works. Abstraction helps in reducing complexity and improving code readability.\n",
      "\n",
      "**Q3: What is Encapsulation in OOP?**\n",
      "\n",
      "**Me:** Encapsulation is the concept of bundling data and its associated methods into a single unit, called a class. It's a way of hiding the internal details of an object from the outside world, making it harder for other parts of the program to access or modify the internal state of the object.\n",
      "\n",
      "**Q4: What is Inheritance in OOP?**\n",
      "\n",
      "**Me:** Inheritance is a mechanism where a new class, called the subclass or derived class, inherits the properties and behavior of an existing class, called the superclass or base class. The subclass inherits all the attributes and methods of the superclass and can also add new attributes and methods or override the ones inherited from the superclass.\n",
      "\n",
      "**Q5: What is Polymorphism in OOP?**\n",
      "\n",
      "**Me:** Polymorphism is the ability of an object to take on multiple forms. It's a way of treating objects of different classes as if they were of the same class. Polymorphism can be achieved through method overloading, method overriding, or operator overloading.\n",
      "\n",
      "**Q6: What is Composition in OOP?**\n",
      "\n",
      "**Me:** Composition is a way of creating objects from other objects. It's a way of breaking down complex systems into smaller, independent objects that are used to build more complex objects. Composition is a form of aggregation where one object owns or contains other objects.\n",
      "\n",
      "**Q7: Why are OOP concepts important?**\n",
      "\n",
      "**Me:** OOP concepts are essential in software development as they help in creating modular, reusable, and maintainable code. They provide a way to organize code in a logical and structured manner, making it easier to understand, modify, and extend the codebase.\n",
      "\n",
      "**Q8: Can you give an example of OOP concepts in real-world scenarios?**\n",
      "\n",
      "**Me:** Yes, for example, consider a car. A car is an object that has properties like color, model, and speed, and behavior like accelerating, braking, and turning. A car can be considered as a class, and its properties and behavior can be encapsulated within it. The different types of cars like sedan, SUV, and truck can be considered as subclasses of the car class, inheriting its properties and behavior. This is an example of OOP concepts like encapsulation, inheritance, and polymorphism.\n",
      "\n",
      "**Q9: How can OOP concepts improve code maintainability?**\n",
      "\n",
      "**Me:** OOP concepts like encapsulation, inheritance, and polymorphism can improve code maintainability by making the code more modular, reusable, and easier to understand. When changes are made to the code, the impact is minimized due to the loose coupling between objects, making it easier to maintain and update the codebase.\n",
      "\n",
      "**Q10: Can you summarize the OOP concepts?**\n",
      "\n",
      "**Me:** In summary, OOP concepts include abstraction, encapsulation, inheritance, polymorphism, and composition. Abstraction hides implementation details, encapsulation bundles data and methods, inheritance allows for code reuse, polymorphism allows for treating objects as if they were of the same class, and composition allows for creating objects from other objects. These concepts help in creating modular, reusable, and maintainable code, making it easier to understand, modify, and extend the codebase.\n"
     ]
    }
   ],
   "source": [
    "from langchain_core.prompts import PromptTemplate\n",
    "from langchain_groq import ChatGroq\n",
    "from langchain_core.output_parsers import StrOutputParser\n",
    "\n",
    "llm = ChatGroq(\n",
    "    groq_api_key=\"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\",\n",
    "    model=\"llama-3.1-8b-instant\",\n",
    "    temperature=0.7\n",
    ")\n",
    "\n",
    "\n",
    "prompt = PromptTemplate(\n",
    "    input_variables=[\"role\", \"topic\", \"format\"],\n",
    "    template=\"\"\"\n",
    "You are a {role}.\n",
    "Explain the topic: {topic}\n",
    "Respond in this format: {format}\n",
    "\"\"\"\n",
    ")\n",
    "\n",
    "chain = prompt | llm | StrOutputParser()\n",
    "\n",
    "\n",
    "inputs = [\n",
    "    {\"role\": \"teacher\", \"topic\": \"Python lists\", \"format\": \"bullet points\"},\n",
    "    {\"role\": \"beginner-friendly tutor\", \"topic\": \"loops in Python\", \"format\": \"simple explanation\"},\n",
    "    {\"role\": \"technical expert\", \"topic\": \"recursion\", \"format\": \"step-by-step\"},\n",
    "    {\"role\": \"interviewer\", \"topic\": \"OOP concepts\", \"format\": \"Q&A format\"}\n",
    "]\n",
    "\n",
    "for i, inp in enumerate(inputs, 1):\n",
    "    print(f\"\\n=== OUTPUT {i} ===\\n\")\n",
    "    result = chain.invoke(inp)\n",
    "    print(result)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "be1e59ba-76e5-4e26-a6d5-5cd4f81f475b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
