{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7c15ad45-f407-4a05-8b89-4970944a4dfc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "===== COMPLEX QUESTION =====\n",
      "\n",
      "=== COMPARISON TABLE ===\n",
      "\n",
      "Model | Time(s) | Output Length (words)\n",
      "---------------------------------------------\n",
      "8B (fast) | 1.333 | 183\n",
      "70B (powerful) | 0 | 0\n",
      "\n",
      "=== 8B (fast) OUTPUT ===\n",
      "\n",
      "To find the average speed for the entire journey, we need to follow these steps:\n",
      "\n",
      "1. **Calculate the total distance traveled**: Since we know the speed and time for each part of the journey, we can calculate the distance traveled in each part.\n",
      "\n",
      "- Distance = Speed x Time\n",
      "- For the first part: Distance1 = 60 km/h x 2 hours = 120 km\n",
      "- For the second part: Distance2 = 80 km/h x 3 hours = 240 km\n",
      "\n",
      "2. **Calculate the total distance**: Add the distances of both parts to get the total distance.\n",
      "- Total D ...\n",
      "\n",
      "=== 70B (powerful) OUTPUT ===\n",
      "\n",
      "ERROR: Error code: 400 - {'error': {'message': 'The model `llama-3.1-70b-versatile` has been decommissioned and is no longer supported. Please refer to https://console.groq.com/docs/deprecations for a recommendation on which model to use instead.', 'type': 'invalid_request_error', 'code': 'model_decommissioned'}} ...\n",
      "\n",
      "===== SIMPLE QUESTION =====\n",
      "\n",
      "=== COMPARISON TABLE ===\n",
      "\n",
      "Model | Time(s) | Output Length (words)\n",
      "---------------------------------------------\n",
      "8B (fast) | 0.356 | 6\n",
      "70B (powerful) | 0 | 0\n",
      "\n",
      "=== 8B (fast) OUTPUT ===\n",
      "\n",
      "The capital of Japan is Tokyo. ...\n",
      "\n",
      "=== 70B (powerful) OUTPUT ===\n",
      "\n",
      "ERROR: Error code: 400 - {'error': {'message': 'The model `llama-3.1-70b-versatile` has been decommissioned and is no longer supported. Please refer to https://console.groq.com/docs/deprecations for a recommendation on which model to use instead.', 'type': 'invalid_request_error', 'code': 'model_decommissioned'}} ...\n"
     ]
    }
   ],
   "source": [
    "from groq import Groq\n",
    "import time\n",
    "\n",
    "client = Groq(api_key=\"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\")\n",
    "\n",
    "\n",
    "models = {\n",
    "    \"8B (fast)\": \"llama-3.1-8b-instant\",\n",
    "    \"70B (powerful)\": \"llama-3.1-70b-versatile\"\n",
    "}\n",
    "\n",
    "\n",
    "def compare_models(prompt, models):\n",
    "    results = []\n",
    "\n",
    "    for name, model in models.items():\n",
    "        try:\n",
    "            start = time.time()\n",
    "\n",
    "            response = client.chat.completions.create(\n",
    "                model=model,\n",
    "                messages=[{\"role\": \"user\", \"content\": prompt}],\n",
    "                temperature=0.7\n",
    "            )\n",
    "\n",
    "            end = time.time()\n",
    "\n",
    "            output = response.choices[0].message.content\n",
    "            response_time = round(end - start, 3)\n",
    "            output_length = len(output.split())\n",
    "\n",
    "            results.append((name, response_time, output_length, output))\n",
    "\n",
    "        except Exception as e:\n",
    "            results.append((name, 0, 0, f\"ERROR: {e}\"))\n",
    "\n",
    "  \n",
    "    print(\"\\n=== COMPARISON TABLE ===\\n\")\n",
    "    print(\"Model | Time(s) | Output Length (words)\")\n",
    "    print(\"-\" * 45)\n",
    "\n",
    "    for r in results:\n",
    "        print(f\"{r[0]} | {r[1]} | {r[2]}\")\n",
    "\n",
    "   \n",
    "    for r in results:\n",
    "        print(f\"\\n=== {r[0]} OUTPUT ===\\n\")\n",
    "        print(r[3][:500], \"...\")  # limit output preview\n",
    "\n",
    "\n",
    "\n",
    "complex_prompt = \"\"\"\n",
    "A train travels 60 km/h for 2 hours and then 80 km/h for 3 hours.\n",
    "What is the average speed for the entire journey? Explain step by step.\n",
    "\"\"\"\n",
    "\n",
    "simple_prompt = \"What is the capital of Japan?\"\n",
    "\n",
    "print(\"\\n===== COMPLEX QUESTION =====\")\n",
    "compare_models(complex_prompt, models)\n",
    "\n",
    "print(\"\\n===== SIMPLE QUESTION =====\")\n",
    "compare_models(simple_prompt, models)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b9299a28-7183-4f48-ae92-5f39d47f9269",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
