{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7f95503e-68dd-4916-93dd-3958539ea000",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: langchain in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (1.3.2)\n",
      "Collecting langchain-community\n",
      "  Downloading langchain_community-0.4.2-py3-none-any.whl.metadata (3.4 kB)\n",
      "Collecting pypdf\n",
      "  Downloading pypdf-6.12.2-py3-none-any.whl.metadata (7.2 kB)\n",
      "Requirement already satisfied: langchain-core<2.0.0,>=1.4.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain) (1.4.0)\n",
      "Requirement already satisfied: langgraph<1.3.0,>=1.2.2 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain) (1.2.2)\n",
      "Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain) (2.12.4)\n",
      "Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (1.33)\n",
      "Requirement already satisfied: langchain-protocol>=0.0.14 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (0.0.15)\n",
      "Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (0.8.5)\n",
      "Requirement already satisfied: packaging>=23.2.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (25.0)\n",
      "Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (6.0.3)\n",
      "Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (9.1.2)\n",
      "Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (4.15.0)\n",
      "Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (0.16.0)\n",
      "Requirement already satisfied: jsonpointer>=1.9 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.0->langchain) (3.0.0)\n",
      "Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.1.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langgraph<1.3.0,>=1.2.2->langchain) (4.1.1)\n",
      "Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langgraph<1.3.0,>=1.2.2->langchain) (1.1.0)\n",
      "Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langgraph<1.3.0,>=1.2.2->langchain) (0.3.15)\n",
      "Requirement already satisfied: xxhash>=3.5.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langgraph<1.3.0,>=1.2.2->langchain) (3.7.0)\n",
      "Requirement already satisfied: ormsgpack>=1.12.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.2->langchain) (1.12.2)\n",
      "Requirement already satisfied: httpx>=0.25.2 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (0.28.1)\n",
      "Requirement already satisfied: orjson>=3.11.5 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (3.11.9)\n",
      "Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (1.0.0)\n",
      "Requirement already satisfied: requests>=2.0.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (2.32.5)\n",
      "Requirement already satisfied: zstandard>=0.23.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (0.24.0)\n",
      "Requirement already satisfied: anyio in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (4.10.0)\n",
      "Requirement already satisfied: certifi in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (2026.4.22)\n",
      "Requirement already satisfied: httpcore==1.* in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (1.0.9)\n",
      "Requirement already satisfied: idna in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (3.11)\n",
      "Requirement already satisfied: h11>=0.16 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (0.16.0)\n",
      "Requirement already satisfied: annotated-types>=0.6.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.41.5 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.5)\n",
      "Requirement already satisfied: typing-inspection>=0.4.2 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)\n",
      "Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-community) (3.13.2)\n",
      "Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain-community)\n",
      "  Downloading httpx_sse-0.4.3-py3-none-any.whl.metadata (9.7 kB)\n",
      "Collecting langchain-classic<2.0.0,>=1.0.7 (from langchain-community)\n",
      "  Downloading langchain_classic-1.0.7-py3-none-any.whl.metadata (5.1 kB)\n",
      "Requirement already satisfied: numpy>=2.1.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-community) (2.3.5)\n",
      "Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-community) (2.12.0)\n",
      "Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-community) (2.0.43)\n",
      "Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.1)\n",
      "Requirement already satisfied: aiosignal>=1.4.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)\n",
      "Requirement already satisfied: attrs>=17.3.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (25.4.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.0)\n",
      "Requirement already satisfied: propcache>=0.2.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.3.1)\n",
      "Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.22.0)\n",
      "Collecting langchain-text-splitters<2.0.0,>=1.1.2 (from langchain-classic<2.0.0,>=1.0.7->langchain-community)\n",
      "  Downloading langchain_text_splitters-1.1.2-py3-none-any.whl.metadata (3.3 kB)\n",
      "Requirement already satisfied: python-dotenv>=0.21.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.1.0)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (3.4.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (2.5.0)\n",
      "Requirement already satisfied: greenlet>=1 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain-community) (3.2.4)\n",
      "Requirement already satisfied: sniffio>=1.1 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from anyio->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (1.3.0)\n",
      "Downloading langchain_community-0.4.2-py3-none-any.whl (2.4 MB)\n",
      "   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--\n",
      "   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--\n",
      "   -------- ------------------------------- 0.5/2.4 MB 2.0 MB/s eta 0:00:01\n",
      "   ----------------- ---------------------- 1.0/2.4 MB 2.2 MB/s eta 0:00:01\n",
      "   ---------------------- ----------------- 1.3/2.4 MB 2.2 MB/s eta 0:00:01\n",
      "   ----------------------------------- ---- 2.1/2.4 MB 2.2 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 2.4/2.4 MB 2.2 MB/s  0:00:01\n",
      "Downloading httpx_sse-0.4.3-py3-none-any.whl (9.0 kB)\n",
      "Downloading langchain_classic-1.0.7-py3-none-any.whl (1.0 MB)\n",
      "   ---------------------------------------- 0.0/1.0 MB ? eta -:--:--\n",
      "   -------------------- ------------------- 0.5/1.0 MB 2.5 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 1.0/1.0 MB 2.5 MB/s  0:00:00\n",
      "Downloading langchain_text_splitters-1.1.2-py3-none-any.whl (35 kB)\n",
      "Downloading pypdf-6.12.2-py3-none-any.whl (343 kB)\n",
      "Installing collected packages: pypdf, httpx-sse, langchain-text-splitters, langchain-classic, langchain-community\n",
      "\n",
      "   ---------------------------------------- 0/5 [pypdf]\n",
      "   ---------------------------------------- 0/5 [pypdf]\n",
      "   ---------------------------------------- 0/5 [pypdf]\n",
      "   ---------------------------------------- 0/5 [pypdf]\n",
      "   -------- ------------------------------- 1/5 [httpx-sse]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   ------------------------ --------------- 3/5 [langchain-classic]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   -------------------------------- ------- 4/5 [langchain-community]\n",
      "   ---------------------------------------- 5/5 [langchain-community]\n",
      "\n",
      "Successfully installed httpx-sse-0.4.3 langchain-classic-1.0.7 langchain-community-0.4.2 langchain-text-splitters-1.1.2 pypdf-6.12.2\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install langchain langchain-community pypdf"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "52bedb51-4caf-4cc2-9a21-7b20fa3b6e14",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\LENOVO\\AppData\\Local\\Temp\\ipykernel_6940\\3826247322.py:1: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.\n",
      "  from langchain_community.document_loaders import PyPDFLoader\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "=== PDF INFO ===\n",
      "\n",
      "Total pages: 15\n",
      "\n",
      "--- Page 1 Metadata ---\n",
      "{'producer': 'Canva', 'creator': 'Canva', 'creationdate': '2026-03-03T19:48:24+00:00', 'title': '6.\\u2060 \\u2060How often do you feel joyful or cheerful? Always Often Sometimes Rarely Never', 'moddate': '2026-03-03T19:48:22+00:00', 'keywords': 'DAHC687TCwU,BAG6nWo4Zso,0', 'author': 'Ak4754', 'source': 'C:\\\\Users\\\\LENOVO\\\\Downloads\\\\survey cdc.pdf', 'total_pages': 15, 'page': 0, 'page_label': '1'}\n",
      "\n",
      "--- First 300 Characters ---\n",
      "S R M  I N S T I T U T E  O F  S C I E N C E  A N D\n",
      "T E C H N O L O G Y  F A C U L T Y  O F  S C I E N C E  A N D\n",
      "H U M A N I T I E S  D E P A R T M E N T  O F  C O M P U T E R\n",
      "A P P L I C A T I O N S  \n",
      "S U B M I T T E D  B Y :\n",
      "S U R V E Y  R E P O R T :\n",
      "C A R E E R  D E V E L O P M E N T  C E N T R\n",
      "\n",
      "=== CHUNKS ===\n",
      "\n",
      "Total chunks: 65\n",
      "\n",
      "--- Chunk 1 ---\n",
      "\n",
      "S R M  I N S T I T U T E  O F  S C I E N C E  A N D\n",
      "T E C H N O L O G Y  F A C U L T Y  O F  S C I E N C E  A N D\n",
      "H U M A N I T I E S  D E P A R T M E N T  O F  C O M P U T E R\n",
      "A P P L I C A T I O N S  \n",
      "S U B M I T T E D  B Y :\n",
      "S U R V E Y  R E P O R T :\n",
      "C A R E E R  D E V E L O P M E N T  C E N T R E  \n",
      "R A 2 4 3 1 2 4 2 0 1 0 1 3 0  \n",
      "R A 2 4 3 1 2 4 2 0 1 0 1 3 2  \n",
      "R A 2 4 3 1 2 4 2 0 1 0 1 3 6\n",
      "\n",
      "--- Chunk 2 ---\n",
      "\n",
      "R A 2 4 3 1 2 4 2 0 1 0 1 3 6  \n",
      "R A 2 4 3 1 2 4 2 0 1 0 1 4 2  \n",
      "R A 2 4 3 1 2 4 2 0 1 0 1 6 9  \n",
      "A L H A  S  Z\n",
      "A R Y A  K\n",
      "A D I T H I  N  V\n",
      "B I N S H A  M U J E E B\n",
      "F A T H I M A  M I N S H A  P\n",
      "U C D 2 4 S 0 3 J – I n d u s t r y O r i e n t e d  E m p l o y a b i l i t y  a n d  L e a d e r s h i p  S k i l l s\n",
      "R E G I S T E R\n",
      "N U M B E R  \n",
      " N a m e\n",
      "\n",
      "--- Chunk 3 ---\n",
      "\n",
      "N U M B E R  \n",
      " N a m e  \n",
      "H A P P I N E S S  A N D  L I F E  S A T I S F A C T I O N  \n",
      "B R A N C H :  S E C T I O N :  C R O O M N O :  4 2 5  B C A . D S\n"
     ]
    }
   ],
   "source": [
    "from langchain_community.document_loaders import PyPDFLoader\n",
    "from langchain_text_splitters import RecursiveCharacterTextSplitter\n",
    "\n",
    "file_path = r\"C:\\Users\\LENOVO\\Downloads\\survey cdc.pdf\"   # replace with your file\n",
    "loader = PyPDFLoader(file_path)\n",
    "pages = loader.load()\n",
    "\n",
    "\n",
    "print(\"\\n=== PDF INFO ===\\n\")\n",
    "print(\"Total pages:\", len(pages))\n",
    "\n",
    "print(\"\\n--- Page 1 Metadata ---\")\n",
    "print(pages[0].metadata)\n",
    "\n",
    "print(\"\\n--- First 300 Characters ---\")\n",
    "print(pages[0].page_content[:300])\n",
    "\n",
    "\n",
    "splitter = RecursiveCharacterTextSplitter(\n",
    "    chunk_size=400,\n",
    "    chunk_overlap=40\n",
    ")\n",
    "\n",
    "chunks = splitter.split_documents(pages)\n",
    "\n",
    "print(\"\\n=== CHUNKS ===\\n\")\n",
    "print(\"Total chunks:\", len(chunks))\n",
    "\n",
    "\n",
    "for i in range(3):\n",
    "    print(f\"\\n--- Chunk {i+1} ---\\n\")\n",
    "    print(chunks[i].page_content)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "06165a99-ad90-4710-ac7c-c87cec3ae393",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
