{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "050b938f-55d3-47a9-99d0-1497762cea72",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading PDF...\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "b0f5e601e1574ea2a7d4b0f78e01ee39",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "import os\n",
    "import tiktoken\n",
    "\n",
    "\n",
    "PDF_PATH = r\"C:\\Users\\LENOVO\\Downloads\\survey cdc.pdf\"\n",
    "os.environ[\"GROQ_API_KEY\"] = \"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\"\n",
    "\n",
    "\n",
    "from langchain_community.document_loaders import PyPDFLoader\n",
    "from langchain_text_splitters import RecursiveCharacterTextSplitter\n",
    "from langchain_community.vectorstores import FAISS\n",
    "from langchain_huggingface import HuggingFaceEmbeddings\n",
    "from langchain_groq import ChatGroq\n",
    "\n",
    "\n",
    "class PDFChatbot:\n",
    "    def __init__(self, pdf_path):\n",
    "        self.pdf_path = pdf_path\n",
    "        self.vectorstore = None\n",
    "        self.llm = ChatGroq(\n",
    "            model=\"llama-3.1-8b-instant\",\n",
    "            temperature=0\n",
    "        )\n",
    "        self.history = []\n",
    "        self.last_docs = []  # store last retrieved chunks\n",
    "\n",
    " \n",
    "    def _count_tokens(self, text):\n",
    "        encoding = tiktoken.get_encoding(\"cl100k_base\")\n",
    "        return len(encoding.encode(text))\n",
    "\n",
    "  \n",
    "    def load_pdf(self):\n",
    "        loader = PyPDFLoader(self.pdf_path)\n",
    "        documents = loader.load()\n",
    "\n",
    "        splitter = RecursiveCharacterTextSplitter(\n",
    "            chunk_size=500,\n",
    "            chunk_overlap=50\n",
    "        )\n",
    "        chunks = splitter.split_documents(documents)\n",
    "\n",
    "        embeddings = HuggingFaceEmbeddings(\n",
    "            model_name=\"sentence-transformers/all-MiniLM-L6-v2\"\n",
    "        )\n",
    "\n",
    "        self.vectorstore = FAISS.from_documents(chunks, embeddings)\n",
    "\n",
    "\n",
    "    def summarize_history(self):\n",
    "        history_text = \"\\n\".join(\n",
    "            [f\"User: {h['q']}\\nAssistant: {h['a']}\" for h in self.history]\n",
    "        )\n",
    "\n",
    "        prompt = f\"\"\"\n",
    "Summarize the following conversation in EXACTLY 3 bullet points:\n",
    "\n",
    "{history_text}\n",
    "\"\"\"\n",
    "\n",
    "        response = self.llm.invoke(prompt)\n",
    "        return response.content\n",
    "\n",
    "  \n",
    "    def show_sources(self):\n",
    "        if not self.last_docs:\n",
    "            return \"No sources available yet.\"\n",
    "\n",
    "        output = \"\\n--- LAST SOURCES ---\\n\"\n",
    "        for i, doc in enumerate(self.last_docs):\n",
    "            page = doc.metadata.get(\"page\", \"Unknown\")\n",
    "            snippet = doc.page_content[:100].replace(\"\\n\", \" \")\n",
    "\n",
    "            output += f\"\\nSource {i+1}\\n\"\n",
    "            output += f\"Page: {page}\\n\"\n",
    "            output += f\"Text: {snippet}...\\n\"\n",
    "\n",
    "        return output\n",
    "\n",
    "    def ask(self, question):\n",
    "       \n",
    "        if question.lower() == \"summary\":\n",
    "            return self.summarize_history()\n",
    "\n",
    "        if question.lower() == \"sources\":\n",
    "            return self.show_sources()\n",
    "\n",
    "        retriever = self.vectorstore.as_retriever(search_kwargs={\"k\": 3})\n",
    "        docs = retriever.invoke(question)\n",
    "\n",
    "        self.last_docs = docs  # store for 'sources' command\n",
    "\n",
    "        context = \"\\n\".join([d.page_content for d in docs])\n",
    "\n",
    "        history_text = \"\\n\".join(\n",
    "            [f\"User: {h['q']}\\nAssistant: {h['a']}\" for h in self.history]\n",
    "        )\n",
    "\n",
    "        prompt = f\"\"\"\n",
    "You are a PDF assistant.\n",
    "\n",
    "Conversation history:\n",
    "{history_text}\n",
    "\n",
    "Context:\n",
    "{context}\n",
    "\n",
    "Rules:\n",
    "- Answer ONLY from context\n",
    "- If not found → \"I could not find this in the document.\"\n",
    "- Keep answers connected to previous conversation\n",
    "\n",
    "Question: {question}\n",
    "\"\"\"\n",
    "\n",
    "        response = self.llm.invoke(prompt)\n",
    "        answer = response.content\n",
    "\n",
    "      \n",
    "        self.history.append({\"q\": question, \"a\": answer})\n",
    "\n",
    "    \n",
    "        full_text = \"\"\n",
    "        for h in self.history:\n",
    "            full_text += f\"User: {h['q']}\\nAssistant: {h['a']}\\n\"\n",
    "\n",
    "        total_tokens = self._count_tokens(full_text)\n",
    "\n",
    "        if total_tokens > 3000:\n",
    "            self.history = self.history[-4:]\n",
    "\n",
    "            new_text = \"\"\n",
    "            for h in self.history:\n",
    "                new_text += f\"User: {h['q']}\\nAssistant: {h['a']}\\n\"\n",
    "\n",
    "            print(\"\\n⚠️ History trimmed to last 4 exchanges\")\n",
    "            print(f\"Tokens after trim: {self._count_tokens(new_text)}\")\n",
    "\n",
    "        return answer\n",
    "\n",
    "\n",
    "\n",
    "chatbot = PDFChatbot(PDF_PATH)\n",
    "\n",
    "print(\"Loading PDF...\")\n",
    "chatbot.load_pdf()\n",
    "print(\"Chatbot Ready!\\n\")\n",
    "\n",
    "\n",
    "questions = [\n",
    "    \"What is the main topic of the document?\",\n",
    "    \"Explain that simply.\",\n",
    "    \"sources\",              # test sources mid-conversation\n",
    "    \"What are key points?\",\n",
    "    \"summary\",              # test summary mid-conversation\n",
    "    \"Give a short conclusion.\"\n",
    "]\n",
    "\n",
    "for i, q in enumerate(questions):\n",
    "    print(\"\\n==============================\")\n",
    "    print(f\"Turn {i+1}\")\n",
    "    print(\"Q:\", q)\n",
    "\n",
    "    ans = chatbot.ask(q)\n",
    "    print(\"A:\", ans)\n",
    "\n",
    "\n",
    "print(\"\\n\\n==============================\")\n",
    "print(\"FINAL HISTORY\")\n",
    "print(\"==============================\")\n",
    "\n",
    "for i, h in enumerate(chatbot.history):\n",
    "    print(f\"\\nTurn {i+1}\")\n",
    "    print(\"User     :\", h[\"q\"])\n",
    "    print(\"Assistant:\", h[\"a\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e83ebe06-91c1-4f18-97a8-65578150d293",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
