{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "9c5e9c43-d535-4389-9eed-1eea5989e5f6",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tiktoken"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "22fba75d-2c34-4315-a4b5-4c319a7a9fb4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading PDF...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "302a8d7592f74fabbdbf371572e89447",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Chatbot Ready!\n",
      "\n",
      "\n",
      "==============================\n",
      "Turn 1\n",
      "Q: What is the main topic of the document?\n",
      "A: The main topic of the document appears to be a survey related to academic and student-related matters, specifically centered on the student community.\n",
      "\n",
      "==============================\n",
      "Turn 2\n",
      "Q: Explain that in simple words.\n",
      "A: The main topic of the document is about students and their experiences. The results of the survey are mostly about what students think and feel, which is helpful for improving their emotional well-being and life satisfaction.\n",
      "\n",
      "==============================\n",
      "Turn 3\n",
      "Q: What are the key points?\n",
      "A: Based on the provided context, the key points of the survey appear to be centered around the happiness and life satisfaction of students. \n",
      "\n",
      "Some of the key points include:\n",
      "\n",
      "1. Personal Information: The survey collects information about the respondent's age group, gender, educational level, and current status.\n",
      "2. Happiness & Emotional Well-being: The survey asks questions about the respondent's emotional well-being, such as whether they have someone to talk to when they feel sad or upset.\n",
      "3. Social Relationships: The survey assesses the respondent's satisfaction with their relationships with family and friends.\n",
      "\n",
      "These key points provide a general idea of the topics covered in the survey, which is focused on understanding the happiness and life satisfaction of students.\n",
      "\n",
      "==============================\n",
      "Turn 4\n",
      "Q: Give a short summary.\n",
      "A: Based on the provided context, the document appears to be a survey related to the happiness and life satisfaction of students. It collects information about their personal lives, emotional well-being, and social relationships. The survey also assesses their ability to handle difficult situations and their sleep patterns.\n",
      "\n",
      "==============================\n",
      "Turn 5\n",
      "Q: What conclusion can we draw?\n",
      "A: Based on the provided context, it appears that the survey respondents are experiencing a moderate to above-average level of happiness in their daily lives. However, the fact that 9 out of 10 respondents feel stressed \"always,\" \"often,\" or \"sometimes\" suggests that they may be struggling with stress and emotional well-being.\n",
      "\n",
      "Additionally, the question about handling difficult situations reveals that many respondents may not be handling them very well, as 4 out of 5 respondents choose \"poorly\" or \"very poorly\" as their answer.\n",
      "\n",
      "Considering these points, it can be concluded that the survey respondents are experiencing a mix of happiness and stress, and may be struggling with emotional well-being and handling difficult situations.\n",
      "\n",
      "\n",
      "==============================\n",
      "FINAL CONVERSATION HISTORY\n",
      "==============================\n",
      "\n",
      "Turn 1\n",
      "User     : What is the main topic of the document?\n",
      "Assistant: The main topic of the document appears to be a survey related to academic and student-related matters, specifically centered on the student community.\n",
      "\n",
      "Turn 2\n",
      "User     : Explain that in simple words.\n",
      "Assistant: The main topic of the document is about students and their experiences. The results of the survey are mostly about what students think and feel, which is helpful for improving their emotional well-being and life satisfaction.\n",
      "\n",
      "Turn 3\n",
      "User     : What are the key points?\n",
      "Assistant: Based on the provided context, the key points of the survey appear to be centered around the happiness and life satisfaction of students. \n",
      "\n",
      "Some of the key points include:\n",
      "\n",
      "1. Personal Information: The survey collects information about the respondent's age group, gender, educational level, and current status.\n",
      "2. Happiness & Emotional Well-being: The survey asks questions about the respondent's emotional well-being, such as whether they have someone to talk to when they feel sad or upset.\n",
      "3. Social Relationships: The survey assesses the respondent's satisfaction with their relationships with family and friends.\n",
      "\n",
      "These key points provide a general idea of the topics covered in the survey, which is focused on understanding the happiness and life satisfaction of students.\n",
      "\n",
      "Turn 4\n",
      "User     : Give a short summary.\n",
      "Assistant: Based on the provided context, the document appears to be a survey related to the happiness and life satisfaction of students. It collects information about their personal lives, emotional well-being, and social relationships. The survey also assesses their ability to handle difficult situations and their sleep patterns.\n",
      "\n",
      "Turn 5\n",
      "User     : What conclusion can we draw?\n",
      "Assistant: Based on the provided context, it appears that the survey respondents are experiencing a moderate to above-average level of happiness in their daily lives. However, the fact that 9 out of 10 respondents feel stressed \"always,\" \"often,\" or \"sometimes\" suggests that they may be struggling with stress and emotional well-being.\n",
      "\n",
      "Additionally, the question about handling difficult situations reveals that many respondents may not be handling them very well, as 4 out of 5 respondents choose \"poorly\" or \"very poorly\" as their answer.\n",
      "\n",
      "Considering these points, it can be concluded that the survey respondents are experiencing a mix of happiness and stress, and may be struggling with emotional well-being and handling difficult situations.\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import tiktoken\n",
    "\n",
    "\n",
    "PDF_PATH = r\"C:\\Users\\LENOVO\\Downloads\\survey cdc.pdf\"\n",
    "os.environ[\"GROQ_API_KEY\"] = \"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\"\n",
    "\n",
    "\n",
    "from langchain_community.document_loaders import PyPDFLoader\n",
    "from langchain_text_splitters import RecursiveCharacterTextSplitter\n",
    "from langchain_community.vectorstores import FAISS\n",
    "from langchain_huggingface import HuggingFaceEmbeddings\n",
    "from langchain_groq import ChatGroq\n",
    "\n",
    "\n",
    "class PDFChatbot:\n",
    "    def __init__(self, pdf_path):\n",
    "        self.pdf_path = pdf_path\n",
    "        self.vectorstore = None\n",
    "        self.llm = ChatGroq(\n",
    "            model=\"llama-3.1-8b-instant\",\n",
    "            temperature=0\n",
    "        )\n",
    "        self.history = []\n",
    "\n",
    " \n",
    "    def _count_tokens(self, text):\n",
    "        encoding = tiktoken.get_encoding(\"cl100k_base\")\n",
    "        return len(encoding.encode(text))\n",
    "\n",
    "  \n",
    "    def load_pdf(self):\n",
    "        loader = PyPDFLoader(self.pdf_path)\n",
    "        documents = loader.load()\n",
    "\n",
    "        splitter = RecursiveCharacterTextSplitter(\n",
    "            chunk_size=500,\n",
    "            chunk_overlap=50\n",
    "        )\n",
    "        chunks = splitter.split_documents(documents)\n",
    "\n",
    "        embeddings = HuggingFaceEmbeddings(\n",
    "            model_name=\"sentence-transformers/all-MiniLM-L6-v2\"\n",
    "        )\n",
    "\n",
    "        self.vectorstore = FAISS.from_documents(chunks, embeddings)\n",
    "\n",
    "   \n",
    "    def ask(self, question):\n",
    "        retriever = self.vectorstore.as_retriever(search_kwargs={\"k\": 3})\n",
    "        docs = retriever.invoke(question)\n",
    "\n",
    "        context = \"\\n\".join([d.page_content for d in docs])\n",
    "\n",
    "      \n",
    "        history_text = \"\\n\".join(\n",
    "            [f\"User: {h['q']}\\nAssistant: {h['a']}\" for h in self.history]\n",
    "        )\n",
    "\n",
    "        prompt = f\"\"\"\n",
    "You are a PDF assistant.\n",
    "\n",
    "Conversation history:\n",
    "{history_text}\n",
    "\n",
    "Context:\n",
    "{context}\n",
    "\n",
    "Rules:\n",
    "- Answer ONLY from context\n",
    "- If not found → \"I could not find this in the document.\"\n",
    "- Keep answers connected to previous conversation if relevant\n",
    "\n",
    "Question: {question}\n",
    "\"\"\"\n",
    "\n",
    "        response = self.llm.invoke(prompt)\n",
    "        answer = response.content\n",
    "\n",
    "       \n",
    "        self.history.append({\"q\": question, \"a\": answer})\n",
    "\n",
    "        full_text = \"\"\n",
    "        for h in self.history:\n",
    "            full_text += f\"User: {h['q']}\\nAssistant: {h['a']}\\n\"\n",
    "\n",
    "        total_tokens = self._count_tokens(full_text)\n",
    "\n",
    "        if total_tokens > 3000:\n",
    "          \n",
    "            self.history = self.history[-4:]\n",
    "\n",
    "          \n",
    "            new_text = \"\"\n",
    "            for h in self.history:\n",
    "                new_text += f\"User: {h['q']}\\nAssistant: {h['a']}\\n\"\n",
    "\n",
    "            print(\"\\n⚠️ History trimmed to last 4 exchanges to stay within token limit\")\n",
    "            print(f\"Tokens after trim: {self._count_tokens(new_text)}\")\n",
    "\n",
    "        return answer\n",
    "\n",
    "\n",
    "\n",
    "chatbot = PDFChatbot(PDF_PATH)\n",
    "\n",
    "print(\"Loading PDF...\")\n",
    "chatbot.load_pdf()\n",
    "print(\"Chatbot Ready!\\n\")\n",
    "\n",
    "\n",
    "questions = [\n",
    "    \"What is the main topic of the document?\",\n",
    "    \"Explain that in simple words.\",\n",
    "    \"What are the key points?\",\n",
    "    \"Give a short summary.\",\n",
    "    \"What conclusion can we draw?\"\n",
    "]\n",
    "\n",
    "for i, q in enumerate(questions):\n",
    "    ans = chatbot.ask(q)\n",
    "\n",
    "    print(\"\\n==============================\")\n",
    "    print(f\"Turn {i+1}\")\n",
    "    print(\"Q:\", q)\n",
    "    print(\"A:\", ans)\n",
    "\n",
    "\n",
    "print(\"\\n\\n==============================\")\n",
    "print(\"FINAL CONVERSATION HISTORY\")\n",
    "print(\"==============================\")\n",
    "\n",
    "for i, h in enumerate(chatbot.history):\n",
    "    print(f\"\\nTurn {i+1}\")\n",
    "    print(\"User     :\", h[\"q\"])\n",
    "    print(\"Assistant:\", h[\"a\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c4ed7992-c560-44e8-9833-dea3f6c07d05",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
