{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "c3946c0f-397b-4161-be9a-c9767cd68a56",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\LENOVO\\AppData\\Local\\Temp\\ipykernel_13560\\3387743945.py:12: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.\n",
      "  from langchain_community.document_loaders import PyPDFLoader\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading PDF and building vector store...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "c1a1b3f7a74e430b989beb5362708042",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Ready!\n",
      "\n",
      "\n",
      "Turn 1\n",
      "Q: What is the main topic of the document?\n",
      "A: The main topic of the document appears to be a survey related to academic and student-related matters, specifically centered on the student community.\n",
      "\n",
      "Turn 2\n",
      "Q: Can you explain that in simple terms?\n",
      "A: Most respondents are happy with their daily lives, which contributes to their overall well-being and life satisfaction. The survey results are mainly from students, and the findings are relevant to their experiences and perspectives.\n",
      "\n",
      "Turn 3\n",
      "Q: What are the key points related to it?\n",
      "A: Based on the provided context, the key points related to the document are:\n",
      "\n",
      "1. The majority of respondents (7.55.1%) rated their physical health as \"good\".\n",
      "2. A significant percentage (30.4%) rated their health as \"average\".\n",
      "3. Only a very small percentage of respondents reported being very dissatisfied with their health.\n",
      "4. Most respondents (34.8%) share their thoughts and feelings about health and lifestyle.\n",
      "5. A notable percentage (5.8%) of respondents never spend time doing enjoyable activities.\n",
      "6. The majority of respondents (40.6%) spend time doing activities they enjoy, which is the highest percentage.\n",
      "\n",
      "These points highlight the overall satisfaction and engagement of the respondents with their physical health and lifestyle.\n",
      "\n",
      "Turn 4\n",
      "Q: Give a short summary based on that.\n",
      "A: Based on the provided context, the survey is largely centered on the student community, and the findings are highly relevant to their experiences and perspectives. The majority of respondents are students, and the data mainly reflects their experiences and opinions. The key points highlight the overall satisfaction and engagement of the respondents with their physical health and lifestyle, with most respondents reporting good physical health and spending time doing enjoyable activities.\n",
      "\n",
      "Turn 5\n",
      "Q: What conclusion can we draw from this?\n",
      "A: Based on the provided context, we can draw the conclusion that respondents experience moderate to above-average happiness in their daily lives. This is evident from the open-ended question that states \"Overall, respondents experience *moderate to above-average happiness* in daily life.\"\n",
      "\n",
      "\n",
      "==============================\n",
      "FULL CONVERSATION HISTORY\n",
      "==============================\n",
      "\n",
      "Turn 1\n",
      "User     : What is the main topic of the document?\n",
      "Assistant: The main topic of the document appears to be a survey related to academic and student-related matters, specifically centered on the student community.\n",
      "\n",
      "Turn 2\n",
      "User     : Can you explain that in simple terms?\n",
      "Assistant: Most respondents are happy with their daily lives, which contributes to their overall well-being and life satisfaction. The survey results are mainly from students, and the findings are relevant to their experiences and perspectives.\n",
      "\n",
      "Turn 3\n",
      "User     : What are the key points related to it?\n",
      "Assistant: Based on the provided context, the key points related to the document are:\n",
      "\n",
      "1. The majority of respondents (7.55.1%) rated their physical health as \"good\".\n",
      "2. A significant percentage (30.4%) rated their health as \"average\".\n",
      "3. Only a very small percentage of respondents reported being very dissatisfied with their health.\n",
      "4. Most respondents (34.8%) share their thoughts and feelings about health and lifestyle.\n",
      "5. A notable percentage (5.8%) of respondents never spend time doing enjoyable activities.\n",
      "6. The majority of respondents (40.6%) spend time doing activities they enjoy, which is the highest percentage.\n",
      "\n",
      "These points highlight the overall satisfaction and engagement of the respondents with their physical health and lifestyle.\n",
      "\n",
      "Turn 4\n",
      "User     : Give a short summary based on that.\n",
      "Assistant: Based on the provided context, the survey is largely centered on the student community, and the findings are highly relevant to their experiences and perspectives. The majority of respondents are students, and the data mainly reflects their experiences and opinions. The key points highlight the overall satisfaction and engagement of the respondents with their physical health and lifestyle, with most respondents reporting good physical health and spending time doing enjoyable activities.\n",
      "\n",
      "Turn 5\n",
      "User     : What conclusion can we draw from this?\n",
      "Assistant: Based on the provided context, we can draw the conclusion that respondents experience moderate to above-average happiness in their daily lives. This is evident from the open-ended question that states \"Overall, respondents experience *moderate to above-average happiness* in daily life.\"\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "\n",
    "\n",
    "PDF_PATH = r\"C:\\Users\\LENOVO\\Downloads\\survey cdc.pdf\"\n",
    "os.environ[\"GROQ_API_KEY\"] = \"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\"\n",
    "\n",
    "\n",
    "from langchain_community.document_loaders import PyPDFLoader\n",
    "from langchain_text_splitters import RecursiveCharacterTextSplitter\n",
    "from langchain_community.vectorstores import FAISS\n",
    "from langchain_huggingface import HuggingFaceEmbeddings\n",
    "from langchain_groq import ChatGroq\n",
    "\n",
    "\n",
    "class PDFChatbot:\n",
    "    def __init__(self, pdf_path):\n",
    "        self.pdf_path = pdf_path\n",
    "        self.vectorstore = None\n",
    "        self.llm = ChatGroq(\n",
    "            model=\"llama-3.1-8b-instant\",\n",
    "            temperature=0\n",
    "        )\n",
    "        self.history = []  # stores full conversation\n",
    "\n",
    "    def load_pdf(self):\n",
    "        loader = PyPDFLoader(self.pdf_path)\n",
    "        documents = loader.load()\n",
    "\n",
    "        splitter = RecursiveCharacterTextSplitter(\n",
    "            chunk_size=500,\n",
    "            chunk_overlap=50\n",
    "        )\n",
    "        chunks = splitter.split_documents(documents)\n",
    "\n",
    "        embeddings = HuggingFaceEmbeddings(\n",
    "            model_name=\"sentence-transformers/all-MiniLM-L6-v2\"\n",
    "        )\n",
    "\n",
    "        self.vectorstore = FAISS.from_documents(chunks, embeddings)\n",
    "\n",
    "    def ask(self, question):\n",
    "        retriever = self.vectorstore.as_retriever(search_kwargs={\"k\": 3})\n",
    "        docs = retriever.invoke(question)\n",
    "\n",
    "        context = \"\\n\".join([d.page_content for d in docs])\n",
    "\n",
    "\n",
    "        history_text = \"\\n\".join(\n",
    "            [f\"User: {h['q']}\\nAssistant: {h['a']}\" for h in self.history]\n",
    "        )\n",
    "\n",
    "        prompt = f\"\"\"\n",
    "You are a PDF assistant.\n",
    "\n",
    "Conversation history:\n",
    "{history_text}\n",
    "\n",
    "Context:\n",
    "{context}\n",
    "\n",
    "Rules:\n",
    "- Answer ONLY from context\n",
    "- If not found → \"I could not find this in the document.\"\n",
    "- Keep answers connected to previous conversation if relevant\n",
    "\n",
    "Question: {question}\n",
    "\"\"\"\n",
    "\n",
    "        response = self.llm.invoke(prompt)\n",
    "\n",
    "        answer = response.content\n",
    "\n",
    "      \n",
    "        self.history.append({\"q\": question, \"a\": answer})\n",
    "\n",
    "        return answer\n",
    "\n",
    "\n",
    "\n",
    "chatbot = PDFChatbot(PDF_PATH)\n",
    "\n",
    "print(\"Loading PDF and building vector store...\")\n",
    "chatbot.load_pdf()\n",
    "print(\"Ready!\\n\")\n",
    "\n",
    "questions = [\n",
    "    \"What is the main topic of the document?\",\n",
    "    \"Can you explain that in simple terms?\",\n",
    "    \"What are the key points related to it?\",\n",
    "    \"Give a short summary based on that.\",\n",
    "    \"What conclusion can we draw from this?\"\n",
    "]\n",
    "\n",
    "for i, q in enumerate(questions):\n",
    "    answer = chatbot.ask(q)\n",
    "\n",
    "    print(f\"\\nTurn {i+1}\")\n",
    "    print(\"Q:\", q)\n",
    "    print(\"A:\", answer)\n",
    "\n",
    "\n",
    "print(\"\\n\\n==============================\")\n",
    "print(\"FULL CONVERSATION HISTORY\")\n",
    "print(\"==============================\")\n",
    "\n",
    "for i, h in enumerate(chatbot.history):\n",
    "    print(f\"\\nTurn {i+1}\")\n",
    "    print(\"User     :\", h[\"q\"])\n",
    "    print(\"Assistant:\", h[\"a\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a03567ee-4db5-4403-a17c-6cf8b931c1a4",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
