{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "535e4e2d-3d47-4139-ab9f-1abbd59a7c03",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "----- ZERO-SHOT REVIEW -----\n",
      "\n",
      "**Code Review and Feedback**\n",
      "\n",
      "The provided Python code appears to be a simple function that processes a list of numbers by multiplying even numbers by 2 and odd numbers by 3. It then calculates the average of the resulting list and prints a message based on the average value. Finally, it returns the processed list and the average value.\n",
      "\n",
      "Here's a review of the code with some suggestions for improvement:\n",
      "\n",
      "### Code Structure and Readability\n",
      "\n",
      "The code is generally easy to follow, but there are a few areas for improvement:\n",
      "\n",
      "*   The function name `process_numbers` is descriptive, but it could be more specific, such as `double_evens_triple_odds`.\n",
      "*   There are two loops in the code: one to process the input list and another to calculate the average. Consider combining them or simplifying the average calculation.\n",
      "*   The variable names are clear, but `r` is a common variable name that often stands for \"result\" or \"remainder\". Consider using a more descriptive name.\n",
      "\n",
      "### Code Efficiency and Algorithm\n",
      "\n",
      "The current implementation has a time complexity of O(n), which is optimal for this problem. However, the multiplication operations inside the loop can be avoided using list comprehension or a generator expression:\n",
      "\n",
      "*   Instead of manually multiplying each element in the list, consider using a list comprehension or a generator expression to create the new list in one step.\n",
      "*   The average calculation can be simplified by using the `sum` function along with the `len` function for the divisor.\n",
      "\n",
      "### Code Style and Conventions\n",
      "\n",
      "The code follows most of the Python style conventions, but here are a few additional suggestions:\n",
      "\n",
      "*   The `return` statement can be placed on the same line as the function body, unless there are multiple values being returned.\n",
      "*   The `if-else` statement for printing a message can be replaced with a ternary operator for brevity.\n",
      "*   Consider using a more modern Python style with consistent spacing and indentation.\n",
      "\n",
      "Here's an updated version of the code incorporating these suggestions:\n",
      "\n",
      "```python\n",
      "def double_evens_triple_odds(nums):\n",
      "    \"\"\"Process a list of numbers by doubling even numbers and tripling odd numbers.\n",
      "    Return the processed list and the average value.\"\"\"\n",
      "    processed = [num * 2 if num % 2 == 0 else num * 3 for num in nums]\n",
      "    total = sum(processed)\n",
      "    avg = total / len(processed)\n",
      "    \n",
      "    print(\"High average\" if avg > 50 else \"Low average\")\n",
      "    return processed, avg\n",
      "```\n",
      "\n",
      "Note that this updated version uses a list comprehension to create the processed list, which is more concise and efficient than the original implementation.\n",
      "\n",
      "\n",
      "----- FEW-SHOT REVIEW -----\n",
      "\n",
      "Review of the provided code:\n",
      "\n",
      "- The code is well-structured and performs the intended operation.\n",
      "- It processes a list of numbers, doubles even numbers, triples odd numbers, calculates the total sum and average of the processed numbers, and then prints a message based on the average value.\n",
      "\n",
      "However, there are several areas for improvement:\n",
      "\n",
      "1. **Type Hints**: The function parameters and return types should have type hints to make the code more readable and understandable.\n",
      "\n",
      "2. **Input Validation**: The function does not validate its input. If `nums` is not a list or contains non-numerical values, the function will fail. It would be better to add input validation to handle such cases.\n",
      "\n",
      "3. **Separation of Concerns**: The function is performing multiple tasks: processing the numbers, calculating the total and average, and printing the result. It would be better to separate these concerns into different functions.\n",
      "\n",
      "4. **Docstring**: The function does not have a docstring describing its purpose and behavior.\n",
      "\n",
      "5. **Variable Naming**: Some variable names, such as `i`, `r`, are not descriptive. It would be better to use more descriptive names.\n",
      "\n",
      "6. **Type Checking**: In the case where `nums` is empty, the function will fail when trying to divide by zero. It would be better to add a check to handle such cases.\n",
      "\n",
      "7. **Printing**: The function is printing directly to the console. It would be better to return the result and let the caller decide what to do with it.\n",
      "\n",
      "8. **Magic Number**: The number 50 is used in a conditional statement. It would be better to define a constant or a configurable value to make the code more flexible.\n",
      "\n",
      "Here's an example of how the code could be refactored based on these suggestions:\n",
      "\n",
      "```python\n",
      "def process_numbers(nums: list[float]) -> tuple[list[float], float]:\n",
      "    \"\"\"\n",
      "    Process a list of numbers by doubling even numbers and tripling odd numbers, \n",
      "    then calculate the average of the processed numbers.\n",
      "\n",
      "    Args:\n",
      "        nums (list[float]): A list of numbers.\n",
      "\n",
      "    Returns:\n",
      "        tuple[list[float], float]: A tuple containing the processed numbers and their average.\n",
      "    \"\"\"\n",
      "\n",
      "    # Input validation\n",
      "    if not isinstance(nums, list):\n",
      "        raise ValueError(\"Input must be a list\")\n",
      "    if len(nums) == 0:\n",
      "        raise ValueError(\"Input list cannot be empty\")\n",
      "    if not all(isinstance(num, (int, float)) for num in nums):\n",
      "        raise ValueError(\"Input list must contain only numbers\")\n",
      "\n",
      "    # Process numbers\n",
      "    processed_nums = [num * 2 if num % 2 == 0 else num * 3 for num in nums]\n",
      "\n",
      "    # Calculate total and average\n",
      "    total = sum(processed_nums)\n",
      "    avg = total / len(processed_nums)\n",
      "\n",
      "    # Check average and print result\n",
      "    if avg > 50:\n",
      "        print(\"High average\")\n",
      "    else:\n",
      "        print(\"Low average\")\n",
      "\n",
      "    return processed_nums, avg\n",
      "\n",
      "def main():\n",
      "    nums = [1, 2, 3, 4, 5]  # Replace with your numbers\n",
      "    try:\n",
      "        result, avg = process_numbers(nums)\n",
      "        print(\"Processed numbers:\", result)\n",
      "        print(\"Average:\", avg)\n",
      "    except ValueError as e:\n",
      "        print(\"Error:\", str(e))\n",
      "\n",
      "if __name__ == \"__main__\":\n",
      "    main()\n",
      "```\n",
      "\n",
      "This revised version includes type hints, input validation, separation of concerns, docstrings, and more. It also uses a more descriptive variable naming convention and handles potential edge cases. The main function is used to call the process_numbers function and handle any potential errors.\n",
      "\n",
      "\n",
      "----- CHAIN-OF-THOUGHT REVIEW -----\n",
      "\n",
      "**Code Review**\n",
      "\n",
      "### 1. Bugs\n",
      "\n",
      "*   The code does not handle invalid inputs. If the input `nums` is not a list or if it contains non-numeric elements, the code will raise an exception.\n",
      "*   The code does not handle empty input lists. It will still calculate the average, but with a length of 0, which will raise a ZeroDivisionError.\n",
      "*   The code does not handle non-integer inputs. It assumes that the elements of `nums` are integers, but if they are not, the modulo operation and multiplication will raise a TypeError.\n",
      "\n",
      "### 2. Style Improvements\n",
      "\n",
      "*   The function name `process_numbers` is not very descriptive. It should be renamed to something like `calculate_and_check_average`.\n",
      "*   The variable names `i`, `r`, and `total` are not very descriptive. They should be renamed to something like `index`, `result_element`, and `total_sum`.\n",
      "*   The function returns two values: the list of modified numbers and the average. It would be better to return a tuple or a dictionary with these values, so that they can be accessed by name.\n",
      "*   The variable `avg` is used inside the function and returned at the end. It would be better to use a more descriptive variable name, for example `average`.\n",
      "*   The code mixes the concepts of modifying the input list and calculating the average. It would be better to separate these concerns into different functions or operations.\n",
      "*   The function has a side effect: it prints a message to the console. This is not a standard behavior for a function, and it would be better to make it return the result instead of printing it.\n",
      "*   The code uses a mutable list (`result`) to accumulate the modified numbers, but this list is not used outside the function. It would be better to use a list comprehension or a generator expression to calculate the modified numbers directly.\n",
      "\n",
      "Here's an updated version of the code with these improvements:\n",
      "```python\n",
      "def calculate_and_check_average(numbers):\n",
      "    \"\"\"Calculate the average of modified numbers and check if it's high or low.\"\"\"\n",
      "    if not isinstance(numbers, list) or not all(isinstance(x, (int, float)) for x in numbers):\n",
      "        raise ValueError(\"Input must be a list of numbers\")\n",
      "\n",
      "    modified_numbers = [x * 2 if x % 2 == 0 else x * 3 for x in numbers]\n",
      "\n",
      "    if not modified_numbers:\n",
      "        return modified_numbers, None\n",
      "\n",
      "    average = sum(modified_numbers) / len(modified_numbers)\n",
      "\n",
      "    if average > 50:\n",
      "        return modified_numbers, {\"average\": average, \"message\": \"High average\"}\n",
      "    else:\n",
      "        return modified_numbers, {\"average\": average, \"message\": \"Low average\"}\n",
      "```\n",
      "### 3. Security Issues\n",
      "\n",
      "*   The code does not perform any input validation or sanitization. An attacker could potentially pass a large or malicious input that would cause the function to consume excessive resources or raise an exception.\n",
      "*   The code does not protect against integer or floating point overflows. If the input is very large or very small, the resulting numbers may exceed the maximum or minimum limits of the integer or float type, causing an overflow.\n",
      "*   The code does not handle exceptions that may be raised by the input validation or the calculation. If an exception is raised, it could lead to an unexpected termination of the program or a crash.\n",
      "\n",
      "To fix these security issues, you could add input validation and sanitization, use try-except blocks to handle exceptions, and use secure data types (such as NumPy arrays or SciPy vectors) to represent the input and output data.\n"
     ]
    }
   ],
   "source": [
    "from groq import Groq\n",
    "\n",
    "\n",
    "client = Groq(api_key=\"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\")\n",
    "\n",
    "\n",
    "code_to_review = \"\"\"\n",
    "def process_numbers(nums):\n",
    "    result = []\n",
    "    \n",
    "    for i in range(len(nums)):\n",
    "        if nums[i] % 2 == 0:\n",
    "            result.append(nums[i] * 2)\n",
    "        else:\n",
    "            result.append(nums[i] * 3)\n",
    "    \n",
    "    total = 0\n",
    "    for r in result:\n",
    "        total += r\n",
    "    \n",
    "    avg = total / len(result)\n",
    "    \n",
    "    if avg > 50:\n",
    "        print(\"High average\")\n",
    "    else:\n",
    "        print(\"Low average\")\n",
    "    \n",
    "    return result, avg\n",
    "\"\"\"\n",
    "\n",
    "\n",
    "zero_shot_prompt = f\"\"\"\n",
    "Review the following Python code and provide feedback:\n",
    "\n",
    "{code_to_review}\n",
    "\"\"\"\n",
    "\n",
    "\n",
    "few_shot_prompt = f\"\"\"\n",
    "Example Code:\n",
    "def add(a, b):\n",
    "    return a + b\n",
    "\n",
    "Example Review:\n",
    "- Simple and correct function\n",
    "- Missing type hints\n",
    "- Could add input validation\n",
    "\n",
    "Now review this code:\n",
    "\n",
    "{code_to_review}\n",
    "\"\"\"\n",
    "\n",
    "\n",
    "cot_prompt = f\"\"\"\n",
    "Review the following Python code step by step:\n",
    "1. Identify bugs\n",
    "2. Suggest style improvements\n",
    "3. Check for security issues\n",
    "\n",
    "Code:\n",
    "{code_to_review}\n",
    "\"\"\"\n",
    "\n",
    "\n",
    "def get_review(prompt):\n",
    "    response = client.chat.completions.create(\n",
    "        model=\"llama-3.1-8b-instant\",\n",
    "        messages=[{\"role\": \"user\", \"content\": prompt}],\n",
    "    )\n",
    "    return response.choices[0].message.content\n",
    "\n",
    "\n",
    "\n",
    "print(\"----- ZERO-SHOT REVIEW -----\\n\")\n",
    "print(get_review(zero_shot_prompt))\n",
    "\n",
    "print(\"\\n\\n----- FEW-SHOT REVIEW -----\\n\")\n",
    "print(get_review(few_shot_prompt))\n",
    "\n",
    "print(\"\\n\\n----- CHAIN-OF-THOUGHT REVIEW -----\\n\")\n",
    "print(get_review(cot_prompt))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "845a6596-60b3-442a-af6c-093dccc7dd6b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
