{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "8fe6ccbd-22b6-47cf-990b-873f856e999b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Comparison Table:\n",
      "\n",
      "Prompt Type          Input Tokens    Response Time   Output Length\n",
      "----------------------------------------------------------------------\n",
      "Zero-shot            109             1.32            2209\n",
      "Few-shot             127             1.79            3270\n",
      "Chain-of-thought     125             1.84            3544\n"
     ]
    }
   ],
   "source": [
    "import time\n",
    "import tiktoken\n",
    "from groq import Groq\n",
    "\n",
    "\n",
    "client = Groq(api_key=\"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\")\n",
    "enc = tiktoken.get_encoding(\"cl100k_base\")\n",
    "\n",
    "\n",
    "code_to_review = \"\"\"\n",
    "def process_numbers(nums):\n",
    "    result = []\n",
    "    \n",
    "    for i in range(len(nums)):\n",
    "        if nums[i] % 2 == 0:\n",
    "            result.append(nums[i] * 2)\n",
    "        else:\n",
    "            result.append(nums[i] * 3)\n",
    "    \n",
    "    total = 0\n",
    "    for r in result:\n",
    "        total += r\n",
    "    \n",
    "    avg = total / len(result)\n",
    "    \n",
    "    if avg > 50:\n",
    "        print(\"High average\")\n",
    "    else:\n",
    "        print(\"Low average\")\n",
    "    \n",
    "    return result, avg\n",
    "\"\"\"\n",
    "\n",
    "\n",
    "zero_prompt = f\"Review this code:\\n{code_to_review}\"\n",
    "\n",
    "few_prompt = f\"\"\"\n",
    "Example:\n",
    "def add(a,b): return a+b\n",
    "Review: Simple but lacks validation.\n",
    "\n",
    "Now review:\n",
    "{code_to_review}\n",
    "\"\"\"\n",
    "\n",
    "cot_prompt = f\"\"\"\n",
    "Review step by step:\n",
    "1. Bugs\n",
    "2. Style\n",
    "3. Security\n",
    "\n",
    "Code:\n",
    "{code_to_review}\n",
    "\"\"\"\n",
    "\n",
    "prompts = {\n",
    "    \"Zero-shot\": zero_prompt,\n",
    "    \"Few-shot\": few_prompt,\n",
    "    \"Chain-of-thought\": cot_prompt\n",
    "}\n",
    "\n",
    "def evaluate_prompt(prompt):\n",
    "   \n",
    "    input_tokens = len(enc.encode(prompt))\n",
    "    \n",
    "\n",
    "    start = time.time()\n",
    "    \n",
    "    response = client.chat.completions.create(\n",
    "        model=\"llama-3.1-8b-instant\",\n",
    "        messages=[{\"role\": \"user\", \"content\": prompt}],\n",
    "    )\n",
    "    \n",
    "    end = time.time()\n",
    "    \n",
    "    output = response.choices[0].message.content\n",
    "    \n",
    "    response_time = end - start\n",
    "    output_length = len(output)\n",
    "    \n",
    "    return input_tokens, response_time, output_length\n",
    "\n",
    "\n",
    "results = []\n",
    "\n",
    "for name, prompt in prompts.items():\n",
    "    tokens, rtime, out_len = evaluate_prompt(prompt)\n",
    "    results.append((name, tokens, rtime, out_len))\n",
    "\n",
    "\n",
    "print(\"\\nComparison Table:\\n\")\n",
    "print(f\"{'Prompt Type':<20} {'Input Tokens':<15} {'Response Time':<15} {'Output Length'}\")\n",
    "print(\"-\" * 70)\n",
    "\n",
    "for r in results:\n",
    "    print(f\"{r[0]:<20} {r[1]:<15} {r[2]:<15.2f} {r[3]}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0bcaad12-baa1-49fe-962f-65fc654aba76",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
