{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "acd94944-76c3-4df3-b39d-20d2b7aa00f2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "=== STEP 1: QUESTIONS ===\n",
      "\n",
      "Here are four quiz questions on the topic of Python lists:\n",
      "\n",
      "1. What is the syntax for accessing the first element of a list in Python?\n",
      "\n",
      "A) `list[0]`\n",
      "B) `list.first`\n",
      "C) `list(0)`\n",
      "D) `list.at(0)`\n",
      "\n",
      "Answer: A) `list[0]`\n",
      "\n",
      "2. What is the time complexity of inserting an element at the beginning of a Python list using the `insert()` method?\n",
      "\n",
      "A) O(1)\n",
      "B) O(n)\n",
      "C) O(log n)\n",
      "D) O(sqrt(n))\n",
      "\n",
      "Answer: B) O(n)\n",
      "\n",
      "3. What is the difference between `append()` and `extend()` methods in Python lists?\n",
      "\n",
      "A) `append()` appends a list, while `extend()` appends an element.\n",
      "B) `append()` appends an element, while `extend()` appends a list.\n",
      "C) `append()` and `extend()` both append a single element.\n",
      "D) `append()` and `extend()` both append a list.\n",
      "\n",
      "Answer: B) `append()` appends an element, while `extend()` appends a list.\n",
      "\n",
      "4. What is the output of the following Python code?\n",
      "```python\n",
      "my_list = [1, 2, 3]\n",
      "my_list[:] = [4, 5, 6]\n",
      "print(my_list)\n",
      "```\n",
      "A) `[1, 2, 3]`\n",
      "B) `[4, 5, 6]`\n",
      "C) `[1, 2, 3, 4, 5, 6]`\n",
      "D) `TypeError: 'list' object does not support item assignment`\n",
      "\n",
      "Answer: B) `[4, 5, 6]`\n",
      "\n",
      "=== STEP 2: MODEL ANSWERS ===\n",
      "\n",
      "Here are the detailed answers to each question:\n",
      "\n",
      "**1. What is the syntax for accessing the first element of a list in Python?**\n",
      "\n",
      "The correct answer is A) `list[0]`.\n",
      "\n",
      "In Python, lists are zero-indexed, meaning that the first element of a list is at index 0. To access the first element, you can use square brackets `[]` and specify the index `0` as follows:\n",
      "\n",
      "```python\n",
      "my_list = [1, 2, 3]\n",
      "print(my_list[0])  # Output: 1\n",
      "```\n",
      "\n",
      "The other options are incorrect because:\n",
      "\n",
      "* `list.first` is not a valid syntax in Python.\n",
      "* `list(0)` is not a valid syntax in Python. The `list()` function is used to create a new list, not to access an element.\n",
      "* `list.at(0)` is not a valid syntax in Python.\n",
      "\n",
      "**2. What is the time complexity of inserting an element at the beginning of a Python list using the `insert()` method?**\n",
      "\n",
      "The correct answer is B) O(n).\n",
      "\n",
      "In Python, lists are implemented as dynamic arrays, which means that inserting an element at the beginning of the list requires shifting all the existing elements to the right. This operation has a linear time complexity of O(n), where n is the number of elements in the list.\n",
      "\n",
      "Here's an example to illustrate this:\n",
      "\n",
      "```python\n",
      "import timeit\n",
      "\n",
      "def insert_at_beginning(lst):\n",
      "    lst.insert(0, 1)\n",
      "\n",
      "lst = [2, 3, 4, 5]\n",
      "print(timeit.timeit(lambda: insert_at_beginning(lst[:]), number=10000))\n",
      "```\n",
      "\n",
      "This code inserts an element at the beginning of the list 10,000 times and measures the time taken. The output should be around 0.1-0.2 seconds, which is indicative of a linear time complexity.\n",
      "\n",
      "**3. What is the difference between `append()` and `extend()` methods in Python lists?**\n",
      "\n",
      "The correct answer is B) `append()` appends an element, while `extend()` appends a list.\n",
      "\n",
      "In Python, `append()` is used to add a single element to the end of the list, while `extend()` is used to add multiple elements to the end of the list.\n",
      "\n",
      "Here's an example to illustrate the difference:\n",
      "\n",
      "```python\n",
      "my_list = [1, 2, 3]\n",
      "\n",
      "# Append a single element\n",
      "my_list.append(4)\n",
      "print(my_list)  # Output: [1, 2, 3, 4]\n",
      "\n",
      "# Extend a list\n",
      "my_list.extend([5, 6])\n",
      "print(my_list)  # Output: [1, 2, 3, 4, 5, 6]\n",
      "```\n",
      "\n",
      "The other options are incorrect because:\n",
      "\n",
      "* `append()` appends a list, while `extend()` appends an element (this is the opposite of the correct answer).\n",
      "* `append()` and `extend()` both append a single element (this is incorrect, as `append()` appends a single element, while `extend()` appends multiple elements).\n",
      "* `append()` and `extend()` both append a list (this is incorrect, as `append()` appends a single element, while `extend()` appends multiple elements).\n",
      "\n",
      "**4. What is the output of the following Python code?**\n",
      "\n",
      "The correct answer is B) `[4, 5, 6]`.\n",
      "\n",
      "In Python, the `[:]` syntax is used to create a slice of the list, which is a new list that contains a subset of the original list's elements. When we assign a new list to the slice, we are changing the original list.\n",
      "\n",
      "Here's an example to illustrate this:\n",
      "\n",
      "```python\n",
      "my_list = [1, 2, 3]\n",
      "my_list[:] = [4, 5, 6]\n",
      "print(my_list)  # Output: [4, 5, 6]\n",
      "```\n",
      "\n",
      "The other options are incorrect because:\n",
      "\n",
      "* The original list is not preserved, so the output is not `[1, 2, 3]`.\n",
      "* The output is not `[4, 5, 6, 1, 2, 3]`, as the slice assignment does not add elements to the original list.\n",
      "* The code does not raise a `TypeError`, as the slice assignment is a valid operation.\n",
      "\n",
      "=== STEP 3: EVALUATION ===\n",
      "\n",
      "**Score: 0/10**\n",
      "\n",
      "**Feedback:**\n",
      "\n",
      "Unfortunately, the student's answers are completely incorrect. Here's a breakdown of each question:\n",
      "\n",
      "1. The student claims that Python lists cannot store multiple values, which is incorrect. Python lists are a type of data structure that can store multiple values.\n",
      "2. The student claims that Python lists are immutable, which is also incorrect. Python lists are a type of mutable data structure, meaning that their contents can be modified after creation.\n",
      "3. The student's answer to question 3 is not relevant to the question, and their answer to question 4 is incorrect.\n",
      "4. The student's answer to question 4 is incorrect, and their answer to question 3 is not relevant to the question.\n",
      "\n",
      "**Specific feedback for each question:**\n",
      "\n",
      "1. Python lists can store multiple values, and they are not immutable. You can access and modify the elements of a list using indexing and slicing.\n",
      "2. The time complexity of inserting an element at the beginning of a Python list using the `insert()` method is O(n), where n is the number of elements in the list. This is because the list is implemented as a dynamic array, and inserting an element at the beginning requires shifting all the existing elements to the right.\n",
      "3. The `append()` method appends a single element to the end of the list, while the `extend()` method appends multiple elements to the end of the list. You can use `append()` to add a single element, and `extend()` to add multiple elements.\n",
      "4. When you assign a new list to a slice of the original list using `[:]`, you are changing the original list. In this case, the output of the code will be `[4, 5, 6]`.\n"
     ]
    }
   ],
   "source": [
    "from groq import Groq\n",
    "\n",
    "client = Groq(api_key=\"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\")\n",
    "\n",
    "MODEL = \"llama-3.1-8b-instant\"\n",
    "\n",
    "\n",
    "def generate_questions(topic):\n",
    "    prompt = f\"Generate 4 quiz questions on the topic: {topic}\"\n",
    "\n",
    "    response = client.chat.completions.create(\n",
    "        model=MODEL,\n",
    "        messages=[{\"role\": \"user\", \"content\": prompt}],\n",
    "        temperature=0.7\n",
    "    )\n",
    "\n",
    "    return response.choices[0].message.content\n",
    "\n",
    "\n",
    "\n",
    "def generate_answers(questions):\n",
    "    prompt = f\"Provide detailed answers for the following questions:\\n{questions}\"\n",
    "\n",
    "    response = client.chat.completions.create(\n",
    "        model=MODEL,\n",
    "        messages=[{\"role\": \"user\", \"content\": prompt}],\n",
    "        temperature=0.7\n",
    "    )\n",
    "\n",
    "    return response.choices[0].message.content\n",
    "\n",
    "\n",
    "\n",
    "def evaluate_answer(question, model_answer, student_answer):\n",
    "    prompt = f\"\"\"\n",
    "Question: {question}\n",
    "\n",
    "Correct Answer:\n",
    "{model_answer}\n",
    "\n",
    "Student Answer:\n",
    "{student_answer}\n",
    "\n",
    "Give:\n",
    "1. Score out of 10\n",
    "2. Specific feedback\n",
    "\"\"\"\n",
    "\n",
    "    response = client.chat.completions.create(\n",
    "        model=MODEL,\n",
    "        messages=[{\"role\": \"user\", \"content\": prompt}],\n",
    "        temperature=0.3\n",
    "    )\n",
    "\n",
    "    return response.choices[0].message.content\n",
    "\n",
    "\n",
    "topic = \"Python lists\"\n",
    "\n",
    "print(\"\\n=== STEP 1: QUESTIONS ===\\n\")\n",
    "questions = generate_questions(topic)\n",
    "print(questions)\n",
    "\n",
    "print(\"\\n=== STEP 2: MODEL ANSWERS ===\\n\")\n",
    "answers = generate_answers(questions)\n",
    "print(answers)\n",
    "\n",
    "\n",
    "first_question = questions.split(\"\\n\")[0]\n",
    "\n",
    "\n",
    "student_answer = \"Python lists cannot store multiple values and are immutable.\"\n",
    "\n",
    "print(\"\\n=== STEP 3: EVALUATION ===\\n\")\n",
    "evaluation = evaluate_answer(first_question, answers, student_answer)\n",
    "print(evaluation)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bd8c31c5-b18b-44c4-80c9-28abcdfbceb8",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
