{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "18cc8113-c020-4b3e-a6de-ee6e590b5492",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "--- Question 1 ---\n",
      "Q: What is a list in Python?\n",
      "\n",
      "A:\n",
      " **Lists in Python**\n",
      "=====================\n",
      "\n",
      "In Python, a list is a collection of items that can be of any data type, including strings, integers, floats, and other lists. Lists are denoted by square brackets `[]` and are ordered, meaning that the order of items in the list is important.\n",
      "\n",
      "**Defining a List**\n",
      "-------------------\n",
      "\n",
      "A list can be defined in several ways:\n",
      "\n",
      "### 1. Using Square Brackets\n",
      "\n",
      "```python\n",
      "my_list = [1, 2, 3, 4, 5]\n",
      "```\n",
      "\n",
      "### 2. Using the `list()` Function\n",
      "\n",
      "```python\n",
      "my_list = list([1, 2, 3, 4, 5])\n",
      "```\n",
      "\n",
      "### 3. Using a Comprehension\n",
      "\n",
      "```python\n",
      "my_list = [x for x in range(1, 6)]\n",
      "```\n",
      "\n",
      "**Example Use Cases**\n",
      "---------------------\n",
      "\n",
      "### 1. Basic Operations\n",
      "\n",
      "```python\n",
      "my_list = [1, 2, 3, 4, 5]\n",
      "\n",
      "# Accessing an item at a specific index\n",
      "print(my_list[0])  # Output: 1\n",
      "\n",
      "# Modifying an item at a specific index\n",
      "my_list[0] = 10\n",
      "print(my_list)  # Output: [10, 2, 3, 4, 5]\n",
      "\n",
      "# Adding an item to the end of the list\n",
      "my_list.append(6)\n",
      "print(my_list)  # Output: [10, 2, 3, 4, 5, 6]\n",
      "```\n",
      "\n",
      "### 2. Slicing\n",
      "\n",
      "```python\n",
      "my_list = [1, 2, 3, 4, 5]\n",
      "\n",
      "# Slicing a subset of the list\n",
      "print(my_list[1:3])  # Output: [2, 3]\n",
      "\n",
      "# Slicing from the beginning to a specific index\n",
      "print(my_list[:3])  # Output: [1, 2, 3]\n",
      "\n",
      "# Slicing from a specific index to the end\n",
      "print(my_list[2:])  # Output: [3, 4, 5]\n",
      "```\n",
      "\n",
      "### 3. List Methods\n",
      "\n",
      "```python\n",
      "my_list = [1, 2, 3, 4, 5]\n",
      "\n",
      "# Removing the first occurrence of an item\n",
      "my_list.remove(3)\n",
      "print(my_list)  # Output: [1, 2, 4, 5]\n",
      "\n",
      "# Removing the last occurrence of an item\n",
      "my_list.pop()\n",
      "print(my_list)  # Output: [1, 2, 4]\n",
      "\n",
      "# Sorting the list\n",
      "my_list.sort()\n",
      "print(my_list)  # Output: [1, 2, 4]\n",
      "```\n",
      "\n",
      "These are just a few examples of the many features and operations that lists provide in Python. With lists, you can create complex data structures and perform a wide range of tasks in your code.\n",
      "\n",
      "--- Question 2 ---\n",
      "Q: Explain recursion with example in Python\n",
      "\n",
      "A:\n",
      " **Recursion in Python**\n",
      "=======================\n",
      "\n",
      "Recursion is a fundamental concept in computer science where a function calls itself as a subroutine. This allows the function to repeat itself until it reaches a base case that stops the recursion.\n",
      "\n",
      "**Example: Factorial Function**\n",
      "-----------------------------\n",
      "\n",
      "Let's take a classic example of the factorial function, which calculates the product of all positive integers up to a given number `n`.\n",
      "\n",
      "### Iterative Approach\n",
      "\n",
      "Here's how we would implement the factorial function using an iterative approach:\n",
      "```python\n",
      "def factorial_iterative(n):\n",
      "    result = 1\n",
      "    for i in range(1, n + 1):\n",
      "        result *= i\n",
      "    return result\n",
      "```\n",
      "### Recursive Approach\n",
      "\n",
      "Now, let's implement the same function using a recursive approach:\n",
      "```python\n",
      "def factorial_recursive(n):\n",
      "    # Base case: 1! = 1\n",
      "    if n == 1:\n",
      "        return 1\n",
      "    # Recursive case: n! = n * (n-1)!\n",
      "    else:\n",
      "        return n * factorial_recursive(n - 1)\n",
      "```\n",
      "Here's how the recursive function works:\n",
      "\n",
      "1. The function calls itself with a smaller value of `n` (i.e., `n-1`) until it reaches the base case (`n == 1`).\n",
      "2. At each recursive call, the function multiplies the current value of `n` with the result of the recursive call.\n",
      "3. The recursion continues until the base case is reached, at which point the function returns the final result.\n",
      "\n",
      "**Example Use Cases**\n",
      "----------------------\n",
      "\n",
      "Let's test both functions with some examples:\n",
      "```python\n",
      "print(factorial_iterative(5))  # Output: 120\n",
      "print(factorial_recursive(5))  # Output: 120\n",
      "```\n",
      "**Recursion vs Iteration**\n",
      "---------------------------\n",
      "\n",
      "While recursion can be a powerful tool for solving certain problems, it's not always the most efficient approach. In general, recursive functions are:\n",
      "\n",
      "* Less efficient than iterative functions, since each recursive call creates a new stack frame, which can lead to stack overflows for large inputs.\n",
      "* More difficult to debug, since the function call stack can make it harder to understand the flow of execution.\n",
      "\n",
      "However, recursion can be useful when:\n",
      "\n",
      "* The problem has a natural recursive structure, such as tree or graph traversal.\n",
      "* The problem requires a simple, elegant solution.\n",
      "\n",
      "In summary, recursion is a powerful tool for solving certain problems, but it's essential to consider the trade-offs between recursion and iteration before choosing an approach.\n",
      "\n",
      "--- Question 3 ---\n",
      "Q: How does a for loop work in Python?\n",
      "\n",
      "A:\n",
      " **For Loops in Python**\n",
      "==========================\n",
      "\n",
      "A `for` loop in Python is used to iterate over a sequence (such as a list, tuple, dictionary, or string) and perform an action for each item in the sequence.\n",
      "\n",
      "**Basic Syntax**\n",
      "---------------\n",
      "\n",
      "The basic syntax of a `for` loop in Python is:\n",
      "```python\n",
      "for variable in sequence:\n",
      "    # perform an action\n",
      "```\n",
      "Here, `variable` is the name given to each item in the sequence during iteration, and `sequence` is the list, tuple, dictionary, or string that you want to iterate over.\n",
      "\n",
      "**Example**\n",
      "------------\n",
      "\n",
      "Suppose we have a list of fruit names and we want to print each fruit name:\n",
      "```python\n",
      "fruits = ['apple', 'banana', 'cherry']\n",
      "\n",
      "for fruit in fruits:\n",
      "    print(fruit)\n",
      "```\n",
      "In this example, the `for` loop will assign each item in the `fruits` list to the variable `fruit`, and then print each value.\n",
      "\n",
      "**How it Works**\n",
      "----------------\n",
      "\n",
      "Here's a step-by-step breakdown of how a `for` loop works:\n",
      "\n",
      "1. **Initialization**: The loop starts by initializing the `variable` with the first item in the `sequence`.\n",
      "2. **Condition**: The loop checks if the `variable` is still a valid item in the `sequence`. If it is, the loop continues.\n",
      "3. **Action**: The loop performs the specified action (in this case, printing the fruit name).\n",
      "4. **Iteration**: The loop increments the `variable` to the next item in the `sequence`.\n",
      "5. **Repeat**: The loop repeats steps 2-4 until all items in the `sequence` have been processed.\n",
      "\n",
      "**Example Use Cases**\n",
      "---------------------\n",
      "\n",
      "1. **Iterating over a list**: Suppose you have a list of employee names and you want to print each name. You can use a `for` loop to iterate over the list and print each name.\n",
      "2. **Iterating over a dictionary**: Suppose you have a dictionary of student scores and you want to calculate the average score. You can use a `for` loop to iterate over the dictionary and calculate the sum of the scores.\n",
      "3. **Iterating over a string**: Suppose you have a string of characters and you want to count the number of vowels. You can use a `for` loop to iterate over the string and count the vowels.\n",
      "\n",
      "**Tips and Variations**\n",
      "------------------------\n",
      "\n",
      "1. **Break and continue statements**: You can use the `break` statement to exit the loop prematurely, or the `continue` statement to skip the current iteration and move on to the next one.\n",
      "2. **Range function**: You can use the `range()` function to generate a sequence of numbers, allowing you to iterate over a specific range.\n",
      "3. **Generator expressions**: You can use generator expressions to create a sequence of values on-the-fly, making it more memory-efficient than creating a large list or tuple.\n",
      "\n",
      "--- Question 4 ---\n",
      "Q: What is the capital of India?\n",
      "\n",
      "A:\n",
      " The capital of India is New Delhi.\n",
      "\n",
      "--- Question 5 ---\n",
      "Q: Explain Java inheritance\n",
      "\n",
      "A:\n",
      " **Java Inheritance**\n",
      "=====================\n",
      "\n",
      "In Java, inheritance is a mechanism that enables one class to inherit the properties and behavior of another class. The class that is inherited from is called the **parent** or **superclass**, while the class that inherits from it is called the **child** or **subclass**.\n",
      "\n",
      "**Why Inheritance?**\n",
      "--------------------\n",
      "\n",
      "Inheritance is useful for several reasons:\n",
      "\n",
      "1. **Code Reusability**: Inheritance allows you to reuse code by inheriting the common properties and behavior of a class.\n",
      "2. **Hierarchical Representation**: Inheritance enables you to create a hierarchical representation of objects, where a child class is a more specific type of its parent class.\n",
      "3. **Easier Maintenance**: Inheritance makes it easier to modify and maintain code, as changes made to a superclass are automatically applied to its subclasses.\n",
      "\n",
      "**Inheritance in Java**\n",
      "-------------------------\n",
      "\n",
      "In Java, a subclass can extend a superclass using the `extends` keyword. Here's an example:\n",
      "```java\n",
      "// Parent class (Superclass)\n",
      "public class Animal {\n",
      "    private String name;\n",
      "    private int age;\n",
      "\n",
      "    public Animal(String name, int age) {\n",
      "        this.name = name;\n",
      "        this.age = age;\n",
      "    }\n",
      "\n",
      "    public void sound() {\n",
      "        System.out.println(\"The animal makes a sound.\");\n",
      "    }\n",
      "}\n",
      "\n",
      "// Child class (Subclass)\n",
      "public class Dog extends Animal {\n",
      "    public Dog(String name, int age) {\n",
      "        super(name, age); // Calls the constructor of the superclass\n",
      "    }\n",
      "\n",
      "    @Override\n",
      "    public void sound() {\n",
      "        System.out.println(\"The dog barks.\");\n",
      "    }\n",
      "}\n",
      "```\n",
      "In this example, the `Dog` class extends the `Animal` class, inheriting its properties and behavior. The `Dog` class also overrides the `sound()` method to provide its own implementation.\n",
      "\n",
      "**Inheritance Types**\n",
      "----------------------\n",
      "\n",
      "Java supports several types of inheritance:\n",
      "\n",
      "1. **Single Inheritance**: A subclass can extend only one superclass.\n",
      "2. **Multilevel Inheritance**: A subclass can extend a subclass of a superclass.\n",
      "3. **Hierarchical Inheritance**: A superclass can have multiple subclasses.\n",
      "4. **Multiple Inheritance**: A subclass can extend multiple superclasses (using interfaces, but not directly).\n",
      "5. **Hybrid Inheritance**: A combination of multiple inheritance types.\n",
      "\n",
      "**Access Modifiers**\n",
      "----------------------\n",
      "\n",
      "Inheritance also involves access modifiers, which control access to fields and methods in the superclass. A subclass can:\n",
      "\n",
      "1. **Inherit public members** from the superclass.\n",
      "2. **Override public methods** from the superclass.\n",
      "3. **Access package-private members** from the superclass (if they are not private).\n",
      "4. **Not access private members** from the superclass (if they are declared private).\n",
      "\n",
      "**Best Practices**\n",
      "-------------------\n",
      "\n",
      "When using inheritance in Java:\n",
      "\n",
      "1. **Follow the Liskov Substitution Principle** (LSP): A subclass should be substitutable for its superclass.\n",
      "2. **Use inheritance for is-a relationships**: A subclass should represent a more specific type of its superclass.\n",
      "3. **Avoid deep inheritance hierarchies**: Keep the inheritance tree shallow to avoid complexity and maintainability issues.\n",
      "\n",
      "By following these guidelines, you can effectively use inheritance in Java to create robust and maintainable applications.\n"
     ]
    }
   ],
   "source": [
    "from groq import Groq\n",
    "\n",
    "client = Groq(api_key=\"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\")\n",
    "\n",
    "\n",
    "system_prompt = \"\"\"PASTE THE SYSTEM PROMPT HERE\"\"\"\n",
    "\n",
    "\n",
    "questions = [\n",
    "    \"What is a list in Python?\",                 \n",
    "    \"Explain recursion with example in Python\", \n",
    "    \"How does a for loop work in Python?\",       \n",
    "    \"What is the capital of India?\",           \n",
    "    \"Explain Java inheritance\"                   \n",
    "]\n",
    "\n",
    "\n",
    "for i, q in enumerate(questions, 1):\n",
    "    print(f\"\\n--- Question {i} ---\")\n",
    "    print(\"Q:\", q)\n",
    "\n",
    "    response = client.chat.completions.create(\n",
    "        model=\"llama-3.1-8b-instant\",\n",
    "        messages=[\n",
    "            {\"role\": \"system\", \"content\": system_prompt},\n",
    "            {\"role\": \"user\", \"content\": q}\n",
    "        ]\n",
    "    )\n",
    "\n",
    "    print(\"\\nA:\\n\", response.choices[0].message.content)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "25bec5e4-8022-4ebb-810c-3919abe71180",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
