{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "ad9e0455-e7f4-4258-8e01-dbf81e827c16",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: langchain in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (1.3.2)\n",
      "Requirement already satisfied: langchain-community in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (0.4.2)\n",
      "Collecting langchain-huggingface\n",
      "  Downloading langchain_huggingface-1.2.2-py3-none-any.whl.metadata (4.0 kB)\n",
      "Requirement already satisfied: langchain-groq in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (1.1.2)\n",
      "Requirement already satisfied: faiss-cpu in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (1.14.2)\n",
      "Requirement already satisfied: pypdf in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (6.12.2)\n",
      "Requirement already satisfied: langchain-core<2.0.0,>=1.4.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain) (1.4.0)\n",
      "Requirement already satisfied: langgraph<1.3.0,>=1.2.2 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain) (1.2.2)\n",
      "Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain) (2.12.4)\n",
      "Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (1.33)\n",
      "Requirement already satisfied: langchain-protocol>=0.0.14 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (0.0.15)\n",
      "Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (0.8.5)\n",
      "Requirement already satisfied: packaging>=23.2.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (25.0)\n",
      "Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (6.0.3)\n",
      "Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (9.1.2)\n",
      "Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (4.15.0)\n",
      "Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (0.16.0)\n",
      "Requirement already satisfied: jsonpointer>=1.9 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.0->langchain) (3.0.0)\n",
      "Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.1.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langgraph<1.3.0,>=1.2.2->langchain) (4.1.1)\n",
      "Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langgraph<1.3.0,>=1.2.2->langchain) (1.1.0)\n",
      "Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langgraph<1.3.0,>=1.2.2->langchain) (0.3.15)\n",
      "Requirement already satisfied: xxhash>=3.5.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langgraph<1.3.0,>=1.2.2->langchain) (3.7.0)\n",
      "Requirement already satisfied: ormsgpack>=1.12.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.2->langchain) (1.12.2)\n",
      "Requirement already satisfied: httpx>=0.25.2 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (0.28.1)\n",
      "Requirement already satisfied: orjson>=3.11.5 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (3.11.9)\n",
      "Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (1.0.0)\n",
      "Requirement already satisfied: requests>=2.0.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (2.32.5)\n",
      "Requirement already satisfied: zstandard>=0.23.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (0.24.0)\n",
      "Requirement already satisfied: anyio in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (4.10.0)\n",
      "Requirement already satisfied: certifi in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (2026.4.22)\n",
      "Requirement already satisfied: httpcore==1.* in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (1.0.9)\n",
      "Requirement already satisfied: idna in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (3.11)\n",
      "Requirement already satisfied: h11>=0.16 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (0.16.0)\n",
      "Requirement already satisfied: annotated-types>=0.6.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.41.5 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.5)\n",
      "Requirement already satisfied: typing-inspection>=0.4.2 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)\n",
      "Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-community) (3.13.2)\n",
      "Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-community) (0.4.3)\n",
      "Requirement already satisfied: langchain-classic<2.0.0,>=1.0.7 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-community) (1.0.7)\n",
      "Requirement already satisfied: numpy>=2.1.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-community) (2.3.5)\n",
      "Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-community) (2.12.0)\n",
      "Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-community) (2.0.43)\n",
      "Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.1)\n",
      "Requirement already satisfied: aiosignal>=1.4.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)\n",
      "Requirement already satisfied: attrs>=17.3.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (25.4.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.0)\n",
      "Requirement already satisfied: propcache>=0.2.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.3.1)\n",
      "Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.22.0)\n",
      "Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.2 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-classic<2.0.0,>=1.0.7->langchain-community) (1.1.2)\n",
      "Requirement already satisfied: python-dotenv>=0.21.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.1.0)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (3.4.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (2.5.0)\n",
      "Requirement already satisfied: greenlet>=1 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain-community) (3.2.4)\n",
      "Requirement already satisfied: huggingface-hub<2.0.0,>=0.33.4 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-huggingface) (1.16.4)\n",
      "Requirement already satisfied: tokenizers<1.0.0,>=0.19.1 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-huggingface) (0.22.2)\n",
      "Requirement already satisfied: click>=8.4.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (8.4.1)\n",
      "Requirement already satisfied: filelock>=3.10.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (3.20.0)\n",
      "Requirement already satisfied: fsspec>=2023.5.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2025.10.0)\n",
      "Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.5.0)\n",
      "Requirement already satisfied: tqdm>=4.42.1 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (4.67.1)\n",
      "Requirement already satisfied: typer<0.26.0,>=0.20.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.20.0)\n",
      "Requirement already satisfied: shellingham>=1.3.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.5.4)\n",
      "Requirement already satisfied: rich>=10.11.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (14.2.0)\n",
      "Requirement already satisfied: groq<1.0.0,>=0.30.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from langchain-groq) (0.37.1)\n",
      "Requirement already satisfied: distro<2,>=1.7.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (1.9.0)\n",
      "Requirement already satisfied: sniffio in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (1.3.0)\n",
      "Requirement already satisfied: colorama in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from click>=8.4.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.4.6)\n",
      "Requirement already satisfied: markdown-it-py>=2.2.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from rich>=10.11.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2.2.0)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from rich>=10.11.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2.19.2)\n",
      "Requirement already satisfied: mdurl~=0.1 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.1.2)\n",
      "Downloading langchain_huggingface-1.2.2-py3-none-any.whl (31 kB)\n",
      "Installing collected packages: langchain-huggingface\n",
      "Successfully installed langchain-huggingface-1.2.2\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install langchain langchain-community langchain-huggingface langchain-groq faiss-cpu pypdf"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "5d2445dd-dbd8-4bcc-bea8-2cb162437b1b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "-----------------------------\n",
      "Q: What is the main topic of the document?\n",
      "A: The main topic of the document is academic and student-related matters.\n",
      "\n",
      "-----------------------------\n",
      "Q: Give a summary of the document.\n",
      "A: The document is a survey questionnaire focused on happiness and life satisfaction, primarily targeting the student community. It is divided into three sections: \n",
      "\n",
      "- Section A: Personal Information, which includes questions about the respondent's age, gender, educational level, and current status.\n",
      "- Section B: Happiness & Emotional Well-being, which explores the respondent's comfort level in sharing thoughts and feelings with close people.\n",
      "- Section E: Health and Lifestyle, which asks about the respondent's sleep hours per night.\n",
      "\n",
      "The survey aims to gather information about the respondents' personal characteristics, emotional well-being, and lifestyle habits.\n",
      "\n",
      "-----------------------------\n",
      "Q: What are the key points discussed?\n",
      "A: The key points discussed in the given context are:\n",
      "\n",
      "1. The survey is centered on student-related matters and the student community.\n",
      "2. The survey questionnaire covers happiness and life satisfaction.\n",
      "3. The background status of survey respondents includes their age group, gender, educational level, and current status.\n",
      "4. The survey also focuses on happiness and emotional well-being, specifically asking respondents to rate their happiness on a scale of 1-10.\n",
      "\n",
      "-----------------------------\n",
      "Q: Explain one important concept from the document.\n",
      "A: One important concept from the document is \"moderate to above-average happiness\" experienced by respondents in their daily life.\n",
      "\n",
      "-----------------------------\n",
      "Q: What conclusion does the document provide?\n",
      "A: The document does not provide a clear conclusion. It appears to be a survey or questionnaire, providing background information about the respondents and asking various questions about their thoughts, feelings, and behaviors.\n"
     ]
    }
   ],
   "source": [
    "for q in questions:\n",
    "    docs = retriever.invoke(q)   \n",
    "\n",
    "    context = \"\\n\".join([d.page_content for d in docs])\n",
    "\n",
    "    prompt = f\"\"\"\n",
    "Answer the question using ONLY the context below.\n",
    "\n",
    "Context:\n",
    "{context}\n",
    "\n",
    "Question: {q}\n",
    "\"\"\"\n",
    "\n",
    "    response = llm.invoke(prompt)\n",
    "\n",
    "    print(\"\\n-----------------------------\")\n",
    "    print(\"Q:\", q)\n",
    "    print(\"A:\", response.content)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e7513459-f902-4ac8-8334-bd493c12001a",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c3696f2c-80a7-4c0c-932b-bf03329f874c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
