{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7ba2581b-9b2d-4530-aaea-ba6e14545631",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: sentence-transformers in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (5.5.1)\n",
      "Requirement already satisfied: scikit-learn in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (1.7.2)\n",
      "Requirement already satisfied: pandas in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (2.3.3)\n",
      "Requirement already satisfied: transformers<6.0.0,>=4.41.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from sentence-transformers) (5.9.0)\n",
      "Requirement already satisfied: huggingface-hub>=0.23.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from sentence-transformers) (1.16.4)\n",
      "Requirement already satisfied: torch>=1.11.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from sentence-transformers) (2.12.0)\n",
      "Requirement already satisfied: numpy>=1.20.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from sentence-transformers) (2.3.5)\n",
      "Requirement already satisfied: scipy>=1.0.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from sentence-transformers) (1.16.3)\n",
      "Requirement already satisfied: typing_extensions>=4.5.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from sentence-transformers) (4.15.0)\n",
      "Requirement already satisfied: tqdm>=4.0.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from sentence-transformers) (4.67.1)\n",
      "Requirement already satisfied: packaging>=20.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (25.0)\n",
      "Requirement already satisfied: pyyaml>=5.1 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (6.0.3)\n",
      "Requirement already satisfied: regex>=2025.10.22 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.5.9)\n",
      "Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)\n",
      "Requirement already satisfied: typer in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.20.0)\n",
      "Requirement already satisfied: safetensors>=0.4.3 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)\n",
      "Requirement already satisfied: click>=8.4.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.1)\n",
      "Requirement already satisfied: filelock>=3.10.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.20.0)\n",
      "Requirement already satisfied: fsspec>=2023.5.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.10.0)\n",
      "Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.0)\n",
      "Requirement already satisfied: httpx<1,>=0.23.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)\n",
      "Requirement already satisfied: anyio in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.10.0)\n",
      "Requirement already satisfied: certifi in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.4.22)\n",
      "Requirement already satisfied: httpcore==1.* in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)\n",
      "Requirement already satisfied: idna in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.11)\n",
      "Requirement already satisfied: h11>=0.16 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)\n",
      "Requirement already satisfied: shellingham>=1.3.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)\n",
      "Requirement already satisfied: rich>=10.11.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (14.2.0)\n",
      "Requirement already satisfied: joblib>=1.2.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from scikit-learn) (1.5.2)\n",
      "Requirement already satisfied: threadpoolctl>=3.1.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from scikit-learn) (3.5.0)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from pandas) (2025.2)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from pandas) (2025.2)\n",
      "Requirement already satisfied: colorama in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from click>=8.4.0->huggingface-hub>=0.23.0->sentence-transformers) (0.4.6)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)\n",
      "Requirement already satisfied: markdown-it-py>=2.2.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from rich>=10.11.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.2.0)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from rich>=10.11.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.19.2)\n",
      "Requirement already satisfied: mdurl~=0.1 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)\n",
      "Requirement already satisfied: setuptools<82 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from torch>=1.11.0->sentence-transformers) (80.9.0)\n",
      "Requirement already satisfied: sympy>=1.13.3 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)\n",
      "Requirement already satisfied: networkx>=2.5.1 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from torch>=1.11.0->sentence-transformers) (3.5)\n",
      "Requirement already satisfied: jinja2 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)\n",
      "Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)\n",
      "Requirement already satisfied: sniffio>=1.1 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.3.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "3a7f2e26541b43418a7eeaae626b06d4",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Cosine Similarity Between Sentence Pairs:\n",
      "\n",
      "                                                    Sentence 1                                                     Sentence 2     Topic 1     Topic 2  Cosine Similarity\n",
      "            Virat Kohli scored a century in the cricket match.         The bowler delivered a fast yorker to take the wicket.     Cricket     Cricket              0.458\n",
      "            Virat Kohli scored a century in the cricket match.        Cricket fans celebrated the thrilling last over finish.     Cricket     Cricket              0.484\n",
      "            Virat Kohli scored a century in the cricket match. The team practiced batting and fielding before the tournament.     Cricket     Cricket              0.416\n",
      "            Virat Kohli scored a century in the cricket match.      Cooking pasta requires boiling water and preparing sauce.     Cricket     Cooking             -0.006\n",
      "            Virat Kohli scored a century in the cricket match.      The chef added spices to improve the flavor of the curry.     Cricket     Cooking              0.146\n",
      "            Virat Kohli scored a century in the cricket match.        Baking cakes becomes easier with accurate measurements.     Cricket     Cooking              0.073\n",
      "            Virat Kohli scored a century in the cricket match.           Python is widely used for machine learning projects.     Cricket Programming             -0.006\n",
      "            Virat Kohli scored a century in the cricket match.            Functions and loops are basic programming concepts.     Cricket Programming             -0.009\n",
      "            Virat Kohli scored a century in the cricket match.     Debugging code helps programmers identify software errors.     Cricket Programming             -0.007\n",
      "        The bowler delivered a fast yorker to take the wicket.        Cricket fans celebrated the thrilling last over finish.     Cricket     Cricket              0.344\n",
      "        The bowler delivered a fast yorker to take the wicket. The team practiced batting and fielding before the tournament.     Cricket     Cricket              0.444\n",
      "        The bowler delivered a fast yorker to take the wicket.      Cooking pasta requires boiling water and preparing sauce.     Cricket     Cooking              0.101\n",
      "        The bowler delivered a fast yorker to take the wicket.      The chef added spices to improve the flavor of the curry.     Cricket     Cooking              0.212\n",
      "        The bowler delivered a fast yorker to take the wicket.        Baking cakes becomes easier with accurate measurements.     Cricket     Cooking              0.074\n",
      "        The bowler delivered a fast yorker to take the wicket.           Python is widely used for machine learning projects.     Cricket Programming             -0.060\n",
      "        The bowler delivered a fast yorker to take the wicket.            Functions and loops are basic programming concepts.     Cricket Programming             -0.096\n",
      "        The bowler delivered a fast yorker to take the wicket.     Debugging code helps programmers identify software errors.     Cricket Programming             -0.012\n",
      "       Cricket fans celebrated the thrilling last over finish. The team practiced batting and fielding before the tournament.     Cricket     Cricket              0.476\n",
      "       Cricket fans celebrated the thrilling last over finish.      Cooking pasta requires boiling water and preparing sauce.     Cricket     Cooking             -0.053\n",
      "       Cricket fans celebrated the thrilling last over finish.      The chef added spices to improve the flavor of the curry.     Cricket     Cooking              0.112\n",
      "       Cricket fans celebrated the thrilling last over finish.        Baking cakes becomes easier with accurate measurements.     Cricket     Cooking             -0.028\n",
      "       Cricket fans celebrated the thrilling last over finish.           Python is widely used for machine learning projects.     Cricket Programming             -0.030\n",
      "       Cricket fans celebrated the thrilling last over finish.            Functions and loops are basic programming concepts.     Cricket Programming             -0.030\n",
      "       Cricket fans celebrated the thrilling last over finish.     Debugging code helps programmers identify software errors.     Cricket Programming             -0.018\n",
      "The team practiced batting and fielding before the tournament.      Cooking pasta requires boiling water and preparing sauce.     Cricket     Cooking              0.006\n",
      "The team practiced batting and fielding before the tournament.      The chef added spices to improve the flavor of the curry.     Cricket     Cooking              0.138\n",
      "The team practiced batting and fielding before the tournament.        Baking cakes becomes easier with accurate measurements.     Cricket     Cooking              0.018\n",
      "The team practiced batting and fielding before the tournament.           Python is widely used for machine learning projects.     Cricket Programming             -0.019\n",
      "The team practiced batting and fielding before the tournament.            Functions and loops are basic programming concepts.     Cricket Programming             -0.009\n",
      "The team practiced batting and fielding before the tournament.     Debugging code helps programmers identify software errors.     Cricket Programming              0.060\n",
      "     Cooking pasta requires boiling water and preparing sauce.      The chef added spices to improve the flavor of the curry.     Cooking     Cooking              0.215\n",
      "     Cooking pasta requires boiling water and preparing sauce.        Baking cakes becomes easier with accurate measurements.     Cooking     Cooking              0.104\n",
      "     Cooking pasta requires boiling water and preparing sauce.           Python is widely used for machine learning projects.     Cooking Programming              0.127\n",
      "     Cooking pasta requires boiling water and preparing sauce.            Functions and loops are basic programming concepts.     Cooking Programming              0.090\n",
      "     Cooking pasta requires boiling water and preparing sauce.     Debugging code helps programmers identify software errors.     Cooking Programming              0.126\n",
      "     The chef added spices to improve the flavor of the curry.        Baking cakes becomes easier with accurate measurements.     Cooking     Cooking              0.167\n",
      "     The chef added spices to improve the flavor of the curry.           Python is widely used for machine learning projects.     Cooking Programming              0.071\n",
      "     The chef added spices to improve the flavor of the curry.            Functions and loops are basic programming concepts.     Cooking Programming              0.048\n",
      "     The chef added spices to improve the flavor of the curry.     Debugging code helps programmers identify software errors.     Cooking Programming             -0.008\n",
      "       Baking cakes becomes easier with accurate measurements.           Python is widely used for machine learning projects.     Cooking Programming              0.016\n",
      "       Baking cakes becomes easier with accurate measurements.            Functions and loops are basic programming concepts.     Cooking Programming              0.087\n",
      "       Baking cakes becomes easier with accurate measurements.     Debugging code helps programmers identify software errors.     Cooking Programming              0.065\n",
      "          Python is widely used for machine learning projects.            Functions and loops are basic programming concepts. Programming Programming              0.278\n",
      "          Python is widely used for machine learning projects.     Debugging code helps programmers identify software errors. Programming Programming              0.218\n",
      "           Functions and loops are basic programming concepts.     Debugging code helps programmers identify software errors. Programming Programming              0.369\n",
      "\n",
      "Average Similarity (Same Topic): 0.331\n",
      "Average Similarity (Cross Topic): 0.036\n",
      "\n",
      "Verification Successful:\n",
      "Same-topic sentences have higher similarity.\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "import pandas as pd\n",
    "\n",
    "!{sys.executable} -m pip install sentence-transformers scikit-learn pandas\n",
    "\n",
    "from sentence_transformers import SentenceTransformer\n",
    "from sklearn.metrics.pairwise import cosine_similarity\n",
    "\n",
    "sentences = [\n",
    "    \"Virat Kohli scored a century in the cricket match.\",\n",
    "    \"The bowler delivered a fast yorker to take the wicket.\",\n",
    "    \"Cricket fans celebrated the thrilling last over finish.\",\n",
    "    \"The team practiced batting and fielding before the tournament.\",\n",
    "\n",
    "    \"Cooking pasta requires boiling water and preparing sauce.\",\n",
    "    \"The chef added spices to improve the flavor of the curry.\",\n",
    "    \"Baking cakes becomes easier with accurate measurements.\",\n",
    "\n",
    "    \"Python is widely used for machine learning projects.\",\n",
    "    \"Functions and loops are basic programming concepts.\",\n",
    "    \"Debugging code helps programmers identify software errors.\"\n",
    "]\n",
    "\n",
    "topics = [\n",
    "    \"Cricket\",\n",
    "    \"Cricket\",\n",
    "    \"Cricket\",\n",
    "    \"Cricket\",\n",
    "    \"Cooking\",\n",
    "    \"Cooking\",\n",
    "    \"Cooking\",\n",
    "    \"Programming\",\n",
    "    \"Programming\",\n",
    "    \"Programming\"\n",
    "]\n",
    "\n",
    "model = SentenceTransformer(\"all-MiniLM-L6-v2\")\n",
    "\n",
    "embeddings = model.encode(sentences)\n",
    "\n",
    "similarity_matrix = cosine_similarity(embeddings)\n",
    "\n",
    "rows = []\n",
    "\n",
    "for i in range(len(sentences)):\n",
    "    for j in range(i + 1, len(sentences)):\n",
    "        rows.append({\n",
    "            \"Sentence 1\": sentences[i],\n",
    "            \"Sentence 2\": sentences[j],\n",
    "            \"Topic 1\": topics[i],\n",
    "            \"Topic 2\": topics[j],\n",
    "            \"Cosine Similarity\": round(similarity_matrix[i][j], 3)\n",
    "        })\n",
    "\n",
    "df = pd.DataFrame(rows)\n",
    "\n",
    "print(\"\\nCosine Similarity Between Sentence Pairs:\\n\")\n",
    "print(df.to_string(index=False))\n",
    "\n",
    "same_topic = []\n",
    "cross_topic = []\n",
    "\n",
    "for i in range(len(sentences)):\n",
    "    for j in range(i + 1, len(sentences)):\n",
    "\n",
    "        score = similarity_matrix[i][j]\n",
    "\n",
    "        if topics[i] == topics[j]:\n",
    "            same_topic.append(score)\n",
    "        else:\n",
    "            cross_topic.append(score)\n",
    "\n",
    "avg_same = sum(same_topic) / len(same_topic)\n",
    "avg_cross = sum(cross_topic) / len(cross_topic)\n",
    "\n",
    "print(\"\\nAverage Similarity (Same Topic):\", round(avg_same, 3))\n",
    "print(\"Average Similarity (Cross Topic):\", round(avg_cross, 3))\n",
    "\n",
    "if avg_same > avg_cross:\n",
    "    print(\"\\nVerification Successful:\")\n",
    "    print(\"Same-topic sentences have higher similarity.\")\n",
    "else:\n",
    "    print(\"\\nVerification Failed:\")\n",
    "    print(\"Cross-topic similarity is unexpectedly higher.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "41d6ed12-4ddb-480d-9624-d6d350416282",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
