{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "52ab3ba0-1ac7-411a-bd54-40b69a73a5d8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "TOKEN COST COMPARISON\n",
      "\n",
      "+-----------------------+--------------+----------+------------------+\n",
      "| Test Case             |   Characters |   Tokens | Estimated Cost   |\n",
      "+=======================+==============+==========+==================+\n",
      "| 300-word Paragraph    |        18600 |     2101 | $0.00021010      |\n",
      "+-----------------------+--------------+----------+------------------+\n",
      "| 50-line Python Script |         1240 |      400 | $0.00004000      |\n",
      "+-----------------------+--------------+----------+------------------+\n",
      "| 3-turn Conversation   |          299 |       66 | $0.00000660      |\n",
      "+-----------------------+--------------+----------+------------------+\n"
     ]
    }
   ],
   "source": [
    " \n",
    "\n",
    "import tiktoken\n",
    "from tabulate import tabulate\n",
    "\n",
    "\n",
    "def token_cost(text, price_per_million=0.10, model=\"gpt-4o-mini\"):\n",
    "    \"\"\"\n",
    "    Count tokens using tiktoken and estimate API cost.\n",
    "\n",
    "    Args:\n",
    "        text (str): Input text\n",
    "        price_per_million (float): Cost per 1M tokens in USD\n",
    "        model (str): Model encoding to use\n",
    "\n",
    "    Returns:\n",
    "        tuple: (token_count, estimated_cost)\n",
    "    \"\"\"\n",
    "    encoding = tiktoken.encoding_for_model(model)\n",
    "    tokens = encoding.encode(text)\n",
    "\n",
    "    token_count = len(tokens)\n",
    "    estimated_cost = (token_count / 1_000_000) * price_per_million\n",
    "\n",
    "    return token_count, estimated_cost\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "paragraph = \"Artificial intelligence is transforming industries worldwide. \" * 300\n",
    "\n",
    "\n",
    "python_script = \"\\n\".join(\n",
    "    [f\"print('This is line {i}')\" for i in range(1, 51)]\n",
    ")\n",
    "\n",
    "\n",
    "conversation = \"\"\"\n",
    "User: Hello, how are you?\n",
    "Assistant: I am doing well. How can I help you today?\n",
    "\n",
    "User: Can you explain machine learning?\n",
    "Assistant: Machine learning is a branch of AI where systems learn from data.\n",
    "\n",
    "User: Give me an example.\n",
    "Assistant: Spam email filtering is a common example of machine learning.\n",
    "\"\"\"\n",
    "\n",
    "\n",
    "results = []\n",
    "\n",
    "tests = {\n",
    "    \"300-word Paragraph\": paragraph,\n",
    "    \"50-line Python Script\": python_script,\n",
    "    \"3-turn Conversation\": conversation\n",
    "}\n",
    "\n",
    "for name, text in tests.items():\n",
    "    tokens, cost = token_cost(text)\n",
    "\n",
    "    results.append([\n",
    "        name,\n",
    "        len(text),\n",
    "        tokens,\n",
    "        f\"${cost:.8f}\"\n",
    "    ])\n",
    "\n",
    "\n",
    "\n",
    "headers = [\"Test Case\", \"Characters\", \"Tokens\", \"Estimated Cost\"]\n",
    "\n",
    "print(\"\\nTOKEN COST COMPARISON\\n\")\n",
    "print(tabulate(results, headers=headers, tablefmt=\"grid\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "be15ce54-f9e2-4f69-b5bd-879126d4d1ef",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
